export type Locale = "pt-PT" | "pt-BR" | "en" | "es" | "fr" | "it" | "de";

export const content = {
  "pt-PT": {
    meta: {
      title: "Verdelago Resort | Apartamentos T2 e T3 no Algarve — Rui Da Cruz",
      description:
        "Apartamentos T2 e T3 no Verdelago Resort, um empreendimento turístico de 5 estrelas entre Altura e a Praia Verde, Algarve. Acesso direto à praia, SPA, piscinas e Resort Club. Representação por Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direto", sobre: "Sobre", contacto: "Contacto", guia: "Guia", faq: "FAQ", vender: "Vender" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort 5 Estrelas", "T2 e T3", "Acesso Direto à Praia", "Elegível para NHR"],
      title: "Onde o Atlântico encontra a tranquilidade do Algarve",
      lede: "Um santuário costeiro entre Altura e a Praia Verde — natureza preservada, serviços de excelência e uma coleção reduzida de residências.",
      priceFrom: "Desde 880.000 €",
      priceNote: "Apartamentos T2 · Fases 4 a 6",
      specs: [
        { label: "Localização", value: "Altura, Castro Marim" },
        { label: "Tipologias", value: "T2 e T3" },
        { label: "Certificação", value: "Green Globe · Green Key" },
        { label: "Entrega", value: "Fases 4, 5 e 6" },
      ],
      ctaPrimary: "Pedir Mais Informações",
      ctaWhatsapp: "Falar via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Consultor Imobiliário · RE/MAX Vantagem Platina · Certificado RE/MAX Collection",
    },
    narrative: {
      eyebrow: "O Empreendimento",
      paragraphs: [
        "Mais do que um empreendimento, o Verdelago proporciona um estilo de vida sofisticado, onde o conforto, a natureza e os serviços de excelência coexistem em perfeita harmonia — uma das referências do segmento residencial e turístico de luxo no Algarve.",
        "Localizado entre Altura e a Praia Verde, com acesso direto à praia através de passadiços integrados na paisagem natural, este resort de 5 estrelas distingue-se pela baixa densidade construtiva, pela excelência da construção e pela arquitetura contemporânea — um compromisso genuíno com a sustentabilidade, reconhecido internacionalmente pelas certificações Green Globe e Green Key.",
        "O resort disponibiliza um conjunto de infraestruturas e serviços premium: hotel de 5 estrelas, Resort Club, SPA & Wellness, piscinas, ginásio, Kids Club, amplas áreas verdes, restaurantes e segurança e gestão integrada — tudo pensado para uma vida em pleno, a poucos passos de casa.",
        "Seja para residência permanente, segunda habitação ou investimento, o Verdelago Resort oferece uma combinação rara de exclusividade, privacidade e qualidade de vida, numa das últimas paisagens intactas do litoral algarvio.",
      ],
      closing: "O último paraíso do Algarve. Entre a natureza e o mar.",
    },
    amenities: {
      eyebrow: "Em Detalhe",
      items: [
        "Hotel de 5 estrelas", "Resort Club", "SPA & Wellness", "Piscinas exteriores",
        "Ginásio equipado", "Kids Club", "Campos de padel", "Green Park e amplos espaços verdes",
        "Restaurantes e áreas de lazer", "Segurança e gestão integrada do resort",
        "Estacionamento coberto", "Acesso direto à praia por passadiços",
      ],
    },
    gallery: {
      eyebrow: "Galeria", title: "Um lugar único para viver",
      viewCursor: "Ver", viewFullGallery: "Ver Galeria Completa", photos: "fotos",
      photosAndVideo: "fotos + vídeo", playVideo: "Reproduzir vídeo do Verdelago",
      viewPhoto: "Ver foto", previousPhoto: "Foto anterior", nextPhoto: "Próxima foto",
    },
    floorplans: {
      eyebrow: "Plantas", title: "Tipologias T2 e T3", cta: "Ver Plantas",
      credit: "Verdelago Resort · Documento Comercial",
    },
    location: {
      eyebrow: "Localização", title: "Altura, Castro Marim — Algarve",
      text: "No litoral leste do Algarve, entre Altura e a Praia Verde — uma zona rica em natureza, praias intactas e tradição, com acesso direto ao mar através de passadiços integrados na paisagem.",
      mapLink: "Ver no mapa",
    },
    lifestyle: {
      eyebrow: "Viver no Verdelago",
      title: "Onde a vida é feita de pequenos momentos",
      lede: "Mais do que uma morada, o Verdelago propõe um ritmo — entre a praia, a piscina e o verde envolvente, cada dia encontra o seu próprio momento de pausa.",
      moments: ["Cocktails de assinatura ao entardecer", "Praia protegida, a poucos passos de casa", "Kids Club para as manhãs mais tranquilas", "Tratamentos de wellness sob medida", "Pool Club e Beach Club", "Desporto ao ar livre, todo o ano"],
    },
    investment: {
      eyebrow: "Investimento",
      title: "Uma aquisição pensada para render",
      items: [
        { title: "Residente Não Habitual", text: "Portugal oferece um regime fiscal vantajoso para novos residentes — condições a confirmar com o seu consultor fiscal, mas um fator relevante para quem considera o Algarve como base." },
        { title: "Programa de Arrendamento", text: "75% da receita líquida de arrendamento fica com o proprietário; os restantes 25% cobrem a gestão da entidade exploradora do resort — sem preocupação operacional da sua parte." },
        { title: "Estrutura de Pagamento", text: "25.000 € de reserva, 25% na assinatura do CPCV, 35% na conclusão da estrutura, e os restantes 40% na escritura pública." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "Um compromisso genuíno com a sustentabilidade, reconhecido internacionalmente — baixa densidade construtiva, gestão consciente da água e da energia, e respeito pela paisagem natural do Algarve.",
    },
    brochure: {
      eyebrow: "Documentação",
      text: "Descarregue a brochura comercial completa do Verdelago Resort, em português ou inglês.",
    },
    related: {
      eyebrow: "Também Disponível",
      title: "Outras Representações de Rui Da Cruz",
    },
    fase6: {
      eyebrow: "Lançamento",
      title: "Fase 6 — a última fase do Verdelago Resort",
      subtitle: "Uma nova oportunidade para viver o Verdelago",
      p1: "O Verdelago Resort apresenta a Fase 6, a última e derradeira fase de vendas do projeto, agora antecipada para responder à procura por imóveis de maior dimensão e localização privilegiada dentro do resort.",
      p2: "Esta última fase é composta por 21 unidades, incluindo 4 unidades de tipologia T4, cuidadosamente selecionadas para proporcionar uma experiência residencial diferenciadora, integrada na natureza e próxima das principais valências do Verdelago.",
      h1: "Uma localização privilegiada",
      p3: "Os dois lotes que integram esta fase beneficiam de uma localização particularmente valorizada, pela sua proximidade ao Clube, ao SPA e ao acesso à praia.",
      p4: "A conjugação entre espaços generosos, localização e acesso às comodidades do resort torna esta última fase uma oportunidade singular para quem procura uma propriedade num dos destinos mais exclusivos do Algarve.",
      h2: "A última oportunidade de aquisição",
      p5: "Com o lançamento da Fase 6, o Verdelago entra na sua última fase de vendas, representando uma oportunidade para adquirir uma propriedade num resort concebido para proporcionar uma experiência de vida diferenciada, em harmonia com a natureza e junto ao mar.",
      p6: "Conheça as tipologias, localizações e preços disponíveis e descubra as últimas oportunidades de aquisição no Verdelago Resort.",
      p7: "Para mais informações ou para agendar uma visita, entre em contacto connosco.",
      statTotal: "frações nesta fase",
      statAvailable: "ainda disponíveis",
      ctaUnits: "Ver frações e valores",
      ctaContact: "Agendar visita",
      imageAlt: "Clube e SPA do Verdelago Resort",
    },
    unidades: {
      eyebrow: "Unidades",
      title: "Unidades Disponíveis",
      description: "Frações disponíveis por fase, com tipologia e valor.",
      legendToggle: "O que significam estas colunas?",
      legendLoteLabel: "Lote",
      legendLoteText: "o prédio/bloco dentro do resort. Um lote com várias frações é um prédio maior, com vários apartamentos.",
      legendFracaoLabel: "Fração",
      legendFracaoText: "o código oficial da unidade: o primeiro número é o andar (0 = rés-do-chão, 1 = 1.º andar...) e a letra é a posição naquele andar.",
      legendTipologiaLabel: "Tipologia",
      legendTipologiaText: "T2/T3 é o número de quartos; a letra (A, B, C, D) indica uma planta diferente com o mesmo número de quartos — ver as plantas mais acima.",
      colLote: "Lote",
      colFracao: "Fração",
      colTipologia: "Tipologia",
      colValor: "Valor",
      fracoesLabel: "frações",
      verTodas: "ver todas",
      brevemente: "Brevemente",
      vendido: "Vendido",
    },
    featured: {
      eyebrow: "Opções em Destaque",
      title: "Algumas escolhas para começar",
      description: "Uma seleção rápida dentro das unidades disponíveis — a tabela completa está mais abaixo.",
      brevemente: "Brevemente",
    },
    form: {
      eyebrow: "Contacto", title: "Conheça as unidades atualmente disponíveis",
      subtitle: "Tipologias, plantas, tabela de preços e condições de aquisição. Resposta em poucas horas.",
      name: "Nome", countryCode: "Código do país", phoneInvalid: "Número incompleto para o país selecionado.",
      phone: "Telefone / WhatsApp", message: "Mensagem (opcional)",
      consent: "Concordo com o tratamento dos meus dados para fins de contacto comercial.",
      submit: "Pedir Mais Informações", submitting: "A enviar…",
      success: "Recebido. O Rui Da Cruz entrará em contacto em breve.",
      error: "Não foi possível enviar. Tente novamente ou contacte via WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedade de Mediação Imobiliária, S.A.",
      rights: "Representação exclusiva por Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Olá Rui, tenho interesse nos apartamentos do Verdelago Resort, no Algarve. Gostaria de mais informações.",
    lightbox: { close: "Fechar", previous: "Anterior", next: "Próxima", video: "Vídeo" },
  },
  "pt-BR": {
    meta: {
      title: "Verdelago Resort | Apartamentos T2 e T3 no Algarve — Rui Da Cruz",
      description:
        "Apartamentos T2 e T3 no Verdelago Resort, um empreendimento turístico cinco estrelas entre Altura e a Praia Verde, Algarve, Portugal. Acesso direto à praia, spa, piscinas e Resort Club. Representação de Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direto", sobre: "Sobre", contacto: "Contato", guia: "Guia", faq: "FAQ", vender: "Vender" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort Cinco Estrelas", "T2 e T3", "Acesso Direto à Praia", "Elegível para NHR"],
      title: "Onde o Atlântico encontra a tranquilidade do Algarve",
      lede: "Um santuário costeiro entre Altura e a Praia Verde — natureza preservada, serviços de excelência e uma coleção reduzida de residências.",
      priceFrom: "A partir de € 880.000",
      priceNote: "Apartamentos T2 · Fases 4 a 6",
      specs: [
        { label: "Localização", value: "Altura, Castro Marim" },
        { label: "Tipologias", value: "T2 e T3" },
        { label: "Certificação", value: "Green Globe · Green Key" },
        { label: "Entrega", value: "Fases 4, 5 e 6" },
      ],
      ctaPrimary: "Pedir Mais Informações",
      ctaWhatsapp: "Falar pelo WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Consultor Imobiliário · RE/MAX Vantagem Platina · Certificado RE/MAX Collection",
    },
    narrative: {
      eyebrow: "O Empreendimento",
      paragraphs: [
        "Mais do que um empreendimento, o Verdelago proporciona um estilo de vida sofisticado, onde o conforto, a natureza e serviços de excelência coexistem em perfeita harmonia — uma das referências do segmento residencial e turístico de luxo no Algarve.",
        "Localizado entre Altura e a Praia Verde, com acesso direto à praia por meio de passarelas integradas à paisagem natural, esse resort cinco estrelas se destaca pela baixa densidade construtiva, pela excelência da construção e pela arquitetura contemporânea — um compromisso genuíno com a sustentabilidade, reconhecido internacionalmente pelas certificações Green Globe e Green Key.",
        "O resort disponibiliza um conjunto de infraestruturas e serviços premium: hotel cinco estrelas, Resort Club, spa & wellness, piscinas, academia, kids club, amplas áreas verdes, restaurantes e segurança e gestão integrada — tudo pensado para uma vida plena, a poucos passos de casa.",
        "Seja para residência permanente, segunda casa ou investimento, o Verdelago Resort oferece uma combinação rara de exclusividade, privacidade e qualidade de vida, em uma das últimas paisagens intactas do litoral do Algarve.",
      ],
      closing: "O último paraíso do Algarve. Entre a natureza e o mar.",
    },
    amenities: {
      eyebrow: "Em Detalhes",
      items: [
        "Hotel cinco estrelas", "Resort Club", "Spa & wellness", "Piscinas externas",
        "Academia equipada", "Kids club", "Quadras de padel", "Green Park e amplas áreas verdes",
        "Restaurantes e áreas de lazer", "Segurança e gestão integrada do resort",
        "Estacionamento coberto", "Acesso direto à praia por passarelas",
      ],
    },
    gallery: {
      eyebrow: "Galeria", title: "Um lugar único para viver",
      viewCursor: "Ver", viewFullGallery: "Ver Galeria Completa", photos: "fotos",
      photosAndVideo: "fotos + vídeo", playVideo: "Reproduzir vídeo do Verdelago",
      viewPhoto: "Ver foto", previousPhoto: "Foto anterior", nextPhoto: "Próxima foto",
    },
    floorplans: {
      eyebrow: "Plantas", title: "Tipologias T2 e T3", cta: "Ver Plantas",
      credit: "Verdelago Resort · Documento Comercial",
    },
    location: {
      eyebrow: "Localização", title: "Altura, Castro Marim — Algarve",
      text: "No litoral leste do Algarve, entre Altura e a Praia Verde — uma região rica em natureza, praias intactas e tradição, com acesso direto ao mar por passarelas integradas à paisagem.",
      mapLink: "Ver no mapa",
    },
    lifestyle: {
      eyebrow: "Viver no Verdelago",
      title: "Onde a vida é feita de pequenos momentos",
      lede: "Mais do que uma morada, o Verdelago propõe um ritmo — entre a praia, a piscina e o verde envolvente, cada dia encontra o seu próprio momento de pausa.",
      moments: ["Cocktails de assinatura ao entardecer", "Praia protegida, a poucos passos de casa", "Kids Club para as manhãs mais tranquilas", "Tratamentos de wellness sob medida", "Pool Club e Beach Club", "Desporto ao ar livre, todo o ano"],
    },
    investment: {
      eyebrow: "Investimento",
      title: "Uma aquisição pensada para render",
      items: [
        { title: "Residente Não Habitual", text: "Portugal oferece um regime fiscal vantajoso para novos residentes — condições a confirmar com o seu consultor fiscal, mas um fator relevante para quem considera o Algarve como base." },
        { title: "Programa de Arrendamento", text: "75% da receita líquida de arrendamento fica com o proprietário; os restantes 25% cobrem a gestão da entidade exploradora do resort — sem preocupação operacional da sua parte." },
        { title: "Estrutura de Pagamento", text: "25.000 € de reserva, 25% na assinatura do CPCV, 35% na conclusão da estrutura, e os restantes 40% na escritura pública." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "Um compromisso genuíno com a sustentabilidade, reconhecido internacionalmente — baixa densidade construtiva, gestão consciente da água e da energia, e respeito pela paisagem natural do Algarve.",
    },
    brochure: {
      eyebrow: "Documentação",
      text: "Descarregue a brochura comercial completa do Verdelago Resort, em português ou inglês.",
    },
    related: {
      eyebrow: "Também Disponível",
      title: "Outras Representações de Rui Da Cruz",
    },
    fase6: {
      eyebrow: "Lançamento",
      title: "Fase 6 — a última fase do Verdelago Resort",
      subtitle: "Uma nova oportunidade para viver o Verdelago",
      p1: "O Verdelago Resort apresenta a Fase 6, a última e derradeira fase de vendas do projeto, agora antecipada para responder à procura por imóveis de maior dimensão e localização privilegiada dentro do resort.",
      p2: "Esta última fase é composta por 21 unidades, incluindo 4 unidades de tipologia T4, cuidadosamente selecionadas para proporcionar uma experiência residencial diferenciadora, integrada na natureza e próxima das principais valências do Verdelago.",
      h1: "Uma localização privilegiada",
      p3: "Os dois lotes que integram esta fase beneficiam de uma localização particularmente valorizada, pela sua proximidade ao Clube, ao SPA e ao acesso à praia.",
      p4: "A conjugação entre espaços generosos, localização e acesso às comodidades do resort torna esta última fase uma oportunidade singular para quem procura uma propriedade num dos destinos mais exclusivos do Algarve.",
      h2: "A última oportunidade de aquisição",
      p5: "Com o lançamento da Fase 6, o Verdelago entra na sua última fase de vendas, representando uma oportunidade para adquirir uma propriedade num resort concebido para proporcionar uma experiência de vida diferenciada, em harmonia com a natureza e junto ao mar.",
      p6: "Conheça as tipologias, localizações e preços disponíveis e descubra as últimas oportunidades de aquisição no Verdelago Resort.",
      p7: "Para mais informações ou para agendar uma visita, entre em contacto connosco.",
      statTotal: "frações nesta fase",
      statAvailable: "ainda disponíveis",
      ctaUnits: "Ver frações e valores",
      ctaContact: "Agendar visita",
      imageAlt: "Clube e SPA do Verdelago Resort",
    },
    unidades: {
      eyebrow: "Unidades",
      title: "Unidades Disponíveis",
      description: "Frações disponíveis por fase, com tipologia e valor.",
      legendToggle: "O que significam estas colunas?",
      legendLoteLabel: "Lote",
      legendLoteText: "o prédio/bloco dentro do resort. Um lote com várias frações é um prédio maior, com vários apartamentos.",
      legendFracaoLabel: "Fração",
      legendFracaoText: "o código oficial da unidade: o primeiro número é o andar (0 = rés-do-chão, 1 = 1.º andar...) e a letra é a posição naquele andar.",
      legendTipologiaLabel: "Tipologia",
      legendTipologiaText: "T2/T3 é o número de quartos; a letra (A, B, C, D) indica uma planta diferente com o mesmo número de quartos — ver as plantas mais acima.",
      colLote: "Lote",
      colFracao: "Fração",
      colTipologia: "Tipologia",
      colValor: "Valor",
      fracoesLabel: "frações",
      verTodas: "ver todas",
      brevemente: "Brevemente",
      vendido: "Vendido",
    },
    featured: {
      eyebrow: "Opções em Destaque",
      title: "Algumas escolhas para começar",
      description: "Uma seleção rápida dentro das unidades disponíveis — a tabela completa está mais abaixo.",
      brevemente: "Brevemente",
    },
    form: {
      eyebrow: "Contato", title: "Conheça as unidades disponíveis no momento",
      subtitle: "Tipologias, plantas, tabela de preços e condições de compra. Resposta em poucas horas.",
      name: "Nome", countryCode: "Código do país", phoneInvalid: "Número incompleto para o país selecionado.",
      phone: "Telefone / WhatsApp", message: "Mensagem (opcional)",
      consent: "Concordo com o tratamento dos meus dados para fins de contato comercial.",
      submit: "Pedir Mais Informações", submitting: "Enviando…",
      success: "Recebido. Rui Da Cruz entrará em contato em breve.",
      error: "Não foi possível enviar. Tente novamente ou entre em contato pelo WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedade de Mediação Imobiliária, S.A.",
      rights: "Representação exclusiva por Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Olá Rui, tenho interesse nos apartamentos do Verdelago Resort, no Algarve. Gostaria de mais informações.",
    lightbox: { close: "Fechar", previous: "Anterior", next: "Próxima", video: "Vídeo" },
  },
  en: {
    meta: {
      title: "Verdelago Resort | T2 & T3 Apartments in the Algarve — Rui Da Cruz",
      description:
        "T2 and T3 apartments at Verdelago Resort, a 5-star tourist development between Altura and Praia Verde, Algarve. Direct beach access, SPA, pools and Resort Club. Represented by Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direct", sobre: "About", contacto: "Contact", guia: "Guide", faq: "FAQ", vender: "Sell" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["5-Star Resort", "T2 & T3", "Direct Beach Access", "NHR Eligible"],
      title: "Where the Atlantic meets the tranquillity of the Algarve",
      lede: "A coastal sanctuary between Altura and Praia Verde — preserved nature, premium services and a limited collection of residences.",
      priceFrom: "From €880,000",
      priceNote: "T2 Apartments · Phases 4 to 6",
      specs: [
        { label: "Location", value: "Altura, Castro Marim" },
        { label: "Typologies", value: "T2 & T3" },
        { label: "Certification", value: "Green Globe · Green Key" },
        { label: "Delivery", value: "Phases 4, 5 & 6" },
      ],
      ctaPrimary: "Request More Information",
      ctaWhatsapp: "Talk via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Real Estate Consultant · RE/MAX Vantagem Platina · RE/MAX Collection Certified",
    },
    narrative: {
      eyebrow: "The Development",
      paragraphs: [
        "More than a development, Verdelago offers a sophisticated lifestyle where comfort, nature and premium services coexist in perfect harmony — one of the references of the luxury residential and tourism segment in the Algarve.",
        "Located between Altura and Praia Verde, with direct beach access via boardwalks integrated into the natural landscape, this 5-star resort stands out for its low building density, construction excellence and contemporary architecture — a genuine commitment to sustainability, internationally recognised through the Green Globe and Green Key certifications.",
        "The resort offers a range of premium infrastructure and services: a 5-star hotel, Resort Club, SPA & Wellness, swimming pools, gym, Kids Club, extensive green areas, restaurants and integrated security and management — all designed for a life lived fully, just steps from home.",
        "Whether for permanent residence, a second home or investment, Verdelago Resort offers a rare combination of exclusivity, privacy and quality of life, in one of the last untouched landscapes on the Algarve coastline.",
      ],
      closing: "The last paradise in the Algarve. Between nature and the sea.",
    },
    amenities: {
      eyebrow: "In Detail",
      items: [
        "5-star hotel", "Resort Club", "SPA & Wellness", "Outdoor pools",
        "Fully equipped gym", "Kids Club", "Padel courts", "Green Park and extensive green areas",
        "Restaurants and leisure areas", "Integrated resort security and management",
        "Covered parking", "Direct beach access via boardwalks",
      ],
    },
    gallery: {
      eyebrow: "Gallery", title: "A unique place to live",
      viewCursor: "View", viewFullGallery: "View Full Gallery", photos: "photos",
      photosAndVideo: "photos + video", playVideo: "Play Verdelago video",
      viewPhoto: "View photo", previousPhoto: "Previous photo", nextPhoto: "Next photo",
    },
    floorplans: {
      eyebrow: "Floor Plans", title: "T2 & T3 Typologies", cta: "View Plans",
      credit: "Verdelago Resort · Commercial Document",
    },
    location: {
      eyebrow: "Location", title: "Altura, Castro Marim — Algarve",
      text: "On the eastern Algarve coastline, between Altura and Praia Verde — an area rich in nature, unspoiled beaches and tradition, with direct sea access via boardwalks integrated into the landscape.",
      mapLink: "View on map",
    },
    lifestyle: {
      eyebrow: "Living in Verdelago",
      title: "Where life is made up of little moments",
      lede: "More than just a place to stay, Verdelago offers a way of life—between the beach, the pool, and the surrounding greenery, every day has its own moment of respite.",
      moments: ["Signature Cocktails at Dusk", "A sheltered beach, just a few steps from home", "Kids Club for a more peaceful morning", "Customized wellness treatments", "Pool Club and Beach Club", "Outdoor sports, all year round"],
    },
    investment: {
      eyebrow: "Investment",
      title: "An acquisition designed to pay off",
      items: [
        { title: "Non-Habitual Resident", text: "Portugal offers a favorable tax regime for new residents—conditions to be confirmed with your tax advisor, but an important factor for anyone considering the Algarve as a base." },
        { title: "Rental Program", text: "75% of the net rental income goes to the owner; the remaining 25% covers the resort operator’s management costs—with no operational concerns on your part." },
        { title: "Payment Structure", text: "€25,000 deposit, 25% upon signing the CPCV, 35% upon completion of the structure, and the remaining 40% at the time of the public deed." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "A genuine, internationally recognized commitment to sustainability—low building density, responsible water and energy management, and respect for the Algarve’s natural landscape.",
    },
    brochure: {
      eyebrow: "Documentation",
      text: "Download the complete Verdelago Resort brochure in Portuguese or English.",
    },
    related: {
      eyebrow: "Also Available",
      title: "Other Properties Represented by Rui Da Cruz",
    },
    fase6: {
      eyebrow: "Launch",
      title: "Phase 6 — the final phase of the Verdelago Resort",
      subtitle: "A new opportunity to experience Verdelago",
      p1: "Verdelago Resort presents Phase 6, the final and last sales phase of the project, which has now been brought forward to meet the demand for larger properties in prime locations within the resort.",
      p2: "This final phase consists of 21 units, including 4 four-bedroom units, carefully selected to provide a unique living experience, integrated with nature and close to Verdelago’s main amenities.",
      h1: "A prime location",
      p3: "The two lots included in this phase are in a particularly desirable location, thanks to their proximity to the Club, the spa, and access to the beach.",
      p4: "The combination of spacious living areas, prime location, and access to the resort’s amenities makes this final phase a unique opportunity for those seeking a property in one of the Algarve’s most exclusive destinations.",
      h2: "The last chance to purchase",
      p5: "With the launch of Phase 6, Verdelago enters its final sales phase, offering an opportunity to purchase a property in a resort designed to provide a unique lifestyle experience, in harmony with nature and right by the sea.",
      p6: "Explore the available property types, locations, and prices, and discover the latest purchasing opportunities at Verdelago Resort.",
      p7: "For more information or to schedule a visit, please contact us.",
      statTotal: "fractions at this stage",
      statAvailable: "still available",
      ctaUnits: "View fractions and values",
      ctaContact: "Schedule a visit",
      imageAlt: "Verdelago Resort Club and Spa",
    },
    unidades: {
      eyebrow: "Units",
      title: "Available Units",
      description: "Available units by phase, including unit type and price.",
      legendToggle: "What do these columns mean?",
      legendLoteLabel: "Lot",
      legendLoteText: "the building/block within the resort. A lot with multiple units is a larger building containing several apartments.",
      legendFracaoLabel: "Fraction",
      legendFracaoText: "the unit's official code: the first number is the floor (0 = ground floor, 1 = 1st floor...) and the letter indicates the unit's position on that floor.",
      legendTipologiaLabel: "Typology",
      legendTipologiaText: "T2/T3 refers to the number of bedrooms; the letter (A, B, C, D) indicates a different floor plan with the same number of bedrooms—see the floor plans above.",
      colLote: "Lot",
      colFracao: "Fraction",
      colTipologia: "Typology",
      colValor: "Amount",
      fracoesLabel: "fractions",
      verTodas: "see all",
      brevemente: "Coming soon",
      vendido: "Sold",
    },
    featured: {
      eyebrow: "Featured Options",
      title: "A few options to get you started",
      description: "A quick selection from the available units—see the complete table below.",
      brevemente: "Coming soon",
    },
    form: {
      eyebrow: "Contact", title: "Discover the units currently available",
      subtitle: "Typologies, floor plans, pricing and purchase terms. Response within hours.",
      name: "Name", countryCode: "Country code", phoneInvalid: "Incomplete number for the selected country.",
      phone: "Phone / WhatsApp", message: "Message (optional)",
      consent: "I agree to the processing of my data for commercial contact purposes.",
      submit: "Request More Information", submitting: "Sending…",
      success: "Received. Rui Da Cruz will be in touch shortly.",
      error: "Could not send. Please try again or reach out via WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedade de Mediação Imobiliária, S.A.",
      rights: "Exclusively represented by Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Hi Rui, I'm interested in the apartments at Verdelago Resort, in the Algarve. I'd like more information.",
    lightbox: { close: "Close", previous: "Previous", next: "Next", video: "Video" },
  },
  es: {
    meta: {
      title: "Verdelago Resort | Apartamentos T2 y T3 en el Algarve — Rui Da Cruz",
      description:
        "Apartamentos T2 y T3 en Verdelago Resort, un complejo turístico de 5 estrellas entre Altura y Praia Verde, Algarve. Acceso directo a la playa, SPA, piscinas y Resort Club. Representación de Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Directo", sobre: "Acerca de", contacto: "Contacto", guia: "Guía", faq: "FAQ", vender: "Vender" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort de 5 Estrellas", "T2 y T3", "Acceso Directo a la Playa", "Elegible para NHR"],
      title: "Donde el Atlántico se encuentra con la tranquilidad del Algarve",
      lede: "Un santuario costero entre Altura y Praia Verde — naturaleza preservada, servicios de excelencia y una colección reducida de residencias.",
      priceFrom: "Desde 880.000 €",
      priceNote: "Apartamentos T2 · Fases 4 a 6",
      specs: [
        { label: "Ubicación", value: "Altura, Castro Marim" },
        { label: "Tipologías", value: "T2 y T3" },
        { label: "Certificación", value: "Green Globe · Green Key" },
        { label: "Entrega", value: "Fases 4, 5 y 6" },
      ],
      ctaPrimary: "Solicitar Más Información",
      ctaWhatsapp: "Hablar por WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Asesor Inmobiliario · RE/MAX Vantagem Platina · Certificado RE/MAX Collection",
    },
    narrative: {
      eyebrow: "El Complejo",
      paragraphs: [
        "Más que un complejo residencial, Verdelago ofrece un estilo de vida sofisticado, donde el confort, la naturaleza y los servicios de excelencia conviven en perfecta armonía — una de las referencias del segmento residencial y turístico de lujo en el Algarve.",
        "Situado entre Altura y Praia Verde, con acceso directo a la playa a través de pasarelas integradas en el paisaje natural, este resort de 5 estrellas destaca por su baja densidad constructiva, la excelencia de su construcción y su arquitectura contemporánea — un compromiso genuino con la sostenibilidad, reconocido internacionalmente por las certificaciones Green Globe y Green Key.",
        "El resort ofrece un conjunto de infraestructuras y servicios premium: hotel de 5 estrellas, Resort Club, SPA & Wellness, piscinas, gimnasio, Kids Club, amplias zonas verdes, restaurantes y seguridad y gestión integradas — todo pensado para vivir plenamente, a pocos pasos de casa.",
        "Ya sea para residencia permanente, segunda vivienda o inversión, Verdelago Resort ofrece una combinación excepcional de exclusividad, privacidad y calidad de vida, en uno de los últimos paisajes intactos del litoral del Algarve.",
      ],
      closing: "El último paraíso del Algarve. Entre la naturaleza y el mar.",
    },
    amenities: {
      eyebrow: "En Detalle",
      items: [
        "Hotel de 5 estrellas", "Resort Club", "SPA & Wellness", "Piscinas exteriores",
        "Gimnasio equipado", "Kids Club", "Pistas de pádel", "Green Park y amplias zonas verdes",
        "Restaurantes y zonas de ocio", "Seguridad y gestión integrada del resort",
        "Aparcamiento cubierto", "Acceso directo a la playa por pasarelas",
      ],
    },
    gallery: {
      eyebrow: "Galería", title: "Un lugar único para vivir",
      viewCursor: "Ver", viewFullGallery: "Ver Galería Completa", photos: "fotos",
      photosAndVideo: "fotos + vídeo", playVideo: "Reproducir vídeo del Verdelago",
      viewPhoto: "Ver foto", previousPhoto: "Foto anterior", nextPhoto: "Foto siguiente",
    },
    floorplans: {
      eyebrow: "Planos", title: "Tipologías T2 y T3", cta: "Ver Planos",
      credit: "Verdelago Resort · Documento Comercial",
    },
    location: {
      eyebrow: "Ubicación", title: "Altura, Castro Marim — Algarve",
      text: "En el litoral este del Algarve, entre Altura y Praia Verde — una zona rica en naturaleza, playas intactas y tradición, con acceso directo al mar a través de pasarelas integradas en el paisaje.",
      mapLink: "Ver en el mapa",
    },
    lifestyle: {
      eyebrow: "Vivir en Verdelago",
      title: "Donde la vida se compone de pequeños momentos",
      lede: "Más que un lugar donde alojarse, Verdelago te ofrece un ritmo de vida: entre la playa, la piscina y la vegetación que lo rodea, cada día tiene su propio momento de descanso.",
      moments: ["Cócteles de autor al atardecer", "Una playa protegida, a solo unos pasos de casa", "Club infantil para disfrutar de mañanas más tranquilas", "Tratamientos de bienestar a medida", "Club de piscina y club de playa", "Deporte al aire libre, todo el año"],
    },
    investment: {
      eyebrow: "Inversión",
      title: "Una adquisición pensada para generar beneficios",
      items: [
        { title: "Residente no habitual", text: "Portugal ofrece un régimen fiscal ventajoso para los nuevos residentes —condiciones que deben confirmarse con su asesor fiscal—, pero es un factor relevante para quienes se plantean establecer su residencia en el Algarve." },
        { title: "Programa de alquiler", text: "El 75 % de los ingresos netos por alquiler se lo queda el propietario; el 25 % restante cubre los gastos de gestión de la empresa gestora del complejo turístico, sin que ello suponga ninguna preocupación operativa por su parte." },
        { title: "Estructura de pago", text: "25 000 € de reserva, el 25 % al firmar el CPCV, el 35 % al finalizar la estructura y el 40 % restante en la escritura pública." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "Un compromiso genuino con la sostenibilidad, reconocido internacionalmente: baja densidad de construcción, gestión responsable del agua y la energía, y respeto por el paisaje natural del Algarve.",
    },
    brochure: {
      eyebrow: "Documentación",
      text: "Descarga el folleto comercial completo del Verdelago Resort, en portugués o en inglés.",
    },
    related: {
      eyebrow: "También disponible",
      title: "Otros inmuebles representados por Rui Da Cruz",
    },
    fase6: {
      eyebrow: "Lanzamiento",
      title: "Fase 6: la última fase del Verdelago Resort",
      subtitle: "Una nueva oportunidad para disfrutar de Verdelago",
      p1: "Verdelago Resort presenta la Fase 6, la última y definitiva fase de venta del proyecto, que ahora se ha adelantado para dar respuesta a la demanda de viviendas más amplias y con una ubicación privilegiada dentro del complejo.",
      p2: "Esta última fase consta de 21 viviendas, incluidas 4 viviendas de tipo T4, cuidadosamente seleccionadas para ofrecer una experiencia residencial única, integrada en la naturaleza y cerca de las principales instalaciones de Verdelago.",
      h1: "Una ubicación privilegiada",
      p3: "Los dos edificios que forman parte de esta fase gozan de una ubicación especialmente privilegiada, por su proximidad al club, al spa y al acceso a la playa.",
      p4: "La combinación de amplios espacios, la ubicación y el acceso a los servicios del complejo turístico hacen de esta última fase una oportunidad única para quienes buscan una propiedad en uno de los destinos más exclusivos del Algarve.",
      h2: "La última oportunidad de compra",
      p5: "Con el lanzamiento de la Fase 6, Verdelago entra en su última fase de venta, lo que supone una oportunidad para adquirir una vivienda en un complejo turístico diseñado para ofrecer una experiencia de vida única, en armonía con la naturaleza y junto al mar.",
      p6: "Descubre los tipos de viviendas, las ubicaciones y los precios disponibles, y entérate de las últimas oportunidades de compra en Verdelago Resort.",
      p7: "Para obtener más información o concertar una visita, ponte en contacto con nosotros.",
      statTotal: "fracciones en esta fase",
      statAvailable: "aún disponibles",
      ctaUnits: "Ver fracciones y valores",
      ctaContact: "Concertar una visita",
      imageAlt: "Club y spa del Verdelago Resort",
    },
    unidades: {
      eyebrow: "Unidades",
      title: "Unidades disponibles",
      description: "Pisos disponibles por fase, con tipo de vivienda y precio.",
      legendToggle: "¿Qué significan estas columnas?",
      legendLoteLabel: "Lote",
      legendLoteText: "el edificio o bloque dentro del complejo turístico. Una parcela con varias fracciones es un edificio más grande, con varios apartamentos.",
      legendFracaoLabel: "Fracción",
      legendFracaoText: "el código oficial de la vivienda: el primer número corresponde a la planta (0 = planta baja, 1 = 1.ª planta...) y la letra indica la posición dentro de esa planta.",
      legendTipologiaLabel: "Tipología",
      legendTipologiaText: "T2/T3 es el número de habitaciones; la letra (A, B, C, D) indica una distribución diferente con el mismo número de habitaciones — véanse las distribuciones más arriba.",
      colLote: "Lote",
      colFracao: "Fracción",
      colTipologia: "Tipología",
      colValor: "Importe",
      fracoesLabel: "fracciones",
      verTodas: "ver todo",
      brevemente: "Próximamente",
      vendido: "Vendido",
    },
    featured: {
      eyebrow: "Opciones destacadas",
      title: "Algunas opciones para empezar",
      description: "Una selección rápida entre las unidades disponibles; la tabla completa se encuentra más abajo.",
      brevemente: "Próximamente",
    },
    form: {
      eyebrow: "Contacto", title: "Conozca las unidades actualmente disponibles",
      subtitle: "Tipologías, planos, tabla de precios y condiciones de compra. Respuesta en pocas horas.",
      name: "Nombre", countryCode: "Código de país", phoneInvalid: "Número incompleto para el país seleccionado.",
      phone: "Teléfono / WhatsApp", message: "Mensaje (opcional)",
      consent: "Acepto que se traten mis datos con fines de contacto comercial.",
      submit: "Solicitar Más Información", submitting: "Enviando…",
      success: "Recibido. Rui Da Cruz se pondrá en contacto contigo en breve.",
      error: "No se ha podido enviar. Inténtalo de nuevo o contacta por WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedad de Intermediación Inmobiliaria, S.A.",
      rights: "Representación exclusiva a cargo de Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Hola Rui, estoy interesado/a en los apartamentos de Verdelago Resort, en el Algarve. Me gustaría más información.",
    lightbox: { close: "Cerrar", previous: "Anterior", next: "Siguiente", video: "Vídeo" },
  },
  fr: {
    meta: {
      title: "Verdelago Resort | Appartements T2 et T3 en Algarve — Rui Da Cruz",
      description:
        "Appartements T2 et T3 au Verdelago Resort, un complexe touristique 5 étoiles entre Altura et Praia Verde, en Algarve. Accès direct à la plage, SPA, piscines et Resort Club. Représentation par Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direct", sobre: "À propos", contacto: "Contact", guia: "Guide", faq: "FAQ", vender: "Vendre" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort 5 Étoiles", "T2 et T3", "Accès Direct à la Plage", "Éligible au statut NHR"],
      title: "Là où l'Atlantique rencontre la tranquillité de l'Algarve",
      lede: "Un sanctuaire côtier entre Altura et Praia Verde — nature préservée, services d'excellence et une collection restreinte de résidences.",
      priceFrom: "À partir de 880 000 €",
      priceNote: "Appartements T2 · Phases 4 à 6",
      specs: [
        { label: "Emplacement", value: "Altura, Castro Marim" },
        { label: "Typologies", value: "T2 et T3" },
        { label: "Certification", value: "Green Globe · Green Key" },
        { label: "Livraison", value: "Phases 4, 5 et 6" },
      ],
      ctaPrimary: "Demander Plus d'Informations",
      ctaWhatsapp: "Contacter via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Conseiller Immobilier · RE/MAX Vantagem Platina · Certifié RE/MAX Collection",
    },
    narrative: {
      eyebrow: "Le Complexe",
      paragraphs: [
        "Plus qu'un complexe résidentiel, Verdelago propose un style de vie raffiné, où le confort, la nature et des services d'excellence coexistent en parfaite harmonie — l'une des références du segment résidentiel et touristique de luxe en Algarve.",
        "Situé entre Altura et Praia Verde, avec un accès direct à la plage via des passerelles intégrées au paysage naturel, ce resort 5 étoiles se distingue par sa faible densité de construction, l'excellence de sa construction et son architecture contemporaine — un engagement authentique envers la durabilité, reconnu internationalement par les certifications Green Globe et Green Key.",
        "Le resort propose un ensemble d'infrastructures et de services haut de gamme : hôtel 5 étoiles, Resort Club, SPA & Wellness, piscines, salle de sport, Kids Club, vastes espaces verts, restaurants ainsi qu'une sécurité et une gestion intégrées — tout pensé pour une vie pleinement vécue, à quelques pas de chez soi.",
        "Que ce soit pour une résidence principale, secondaire ou un investissement, Verdelago Resort offre une combinaison rare d'exclusivité, d'intimité et de qualité de vie, dans l'un des derniers paysages intacts du littoral de l'Algarve.",
      ],
      closing: "Le dernier paradis de l'Algarve. Entre la nature et la mer.",
    },
    amenities: {
      eyebrow: "En Détail",
      items: [
        "Hôtel 5 étoiles", "Resort Club", "SPA & Wellness", "Piscines extérieures",
        "Salle de sport équipée", "Kids Club", "Terrains de padel", "Green Park et vastes espaces verts",
        "Restaurants et espaces de loisirs", "Sécurité et gestion intégrées du resort",
        "Parking couvert", "Accès direct à la plage via passerelles",
      ],
    },
    gallery: {
      eyebrow: "Galerie", title: "Un lieu unique où vivre",
      viewCursor: "Voir", viewFullGallery: "Voir la Galerie Complète", photos: "photos",
      photosAndVideo: "photos + vidéo", playVideo: "Lire la vidéo du Verdelago",
      viewPhoto: "Voir la photo", previousPhoto: "Photo précédente", nextPhoto: "Photo suivante",
    },
    floorplans: {
      eyebrow: "Plans", title: "Typologies T2 et T3", cta: "Voir les Plans",
      credit: "Verdelago Resort · Document Commercial",
    },
    location: {
      eyebrow: "Emplacement", title: "Altura, Castro Marim — Algarve",
      text: "Sur le littoral est de l'Algarve, entre Altura et Praia Verde — une région riche en nature, en plages préservées et en tradition, avec un accès direct à la mer via des passerelles intégrées au paysage.",
      mapLink: "Voir sur la carte",
    },
    lifestyle: {
      eyebrow: "Vivre à Verdelago",
      title: "Là où la vie se compose de petits moments",
      lede: "Plus qu'un simple lieu de séjour, le Verdelago vous propose un rythme de vie particulier : entre la plage, la piscine et la verdure environnante, chaque journée offre son propre moment de détente.",
      moments: ["Cocktails maison au coucher du soleil", "Une plage protégée, à deux pas de chez soi", "Le Kids Club pour des matinées plus tranquilles", "Soins bien-être sur mesure", "Pool Club et Beach Club", "Des sports de plein air, toute l'année"],
    },
    investment: {
      eyebrow: "Investissement",
      title: "Une acquisition destinée à être rentable",
      items: [
        { title: "Résident non habituel", text: "Le Portugal propose un régime fiscal avantageux aux nouveaux résidents — des conditions à vérifier auprès de votre conseiller fiscal, mais un élément important à prendre en compte pour ceux qui envisagent de s'installer en Algarve." },
        { title: "Programme de location", text: "75 % des revenus nets locatifs reviennent au propriétaire ; les 25 % restants couvrent les frais de gestion de la société exploitante du complexe touristique — sans que vous ayez à vous soucier de l'aspect opérationnel." },
        { title: "Structure de paiement", text: "25 000 € d'acompte, 25 % à la signature du CPCV, 35 % à l'achèvement du gros œuvre, et les 40 % restants lors de la signature de l'acte notarié." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "Un engagement sincère en faveur du développement durable, reconnu à l'échelle internationale : faible densité de construction, gestion raisonnée de l'eau et de l'énergie, et respect du paysage naturel de l'Algarve.",
    },
    brochure: {
      eyebrow: "Documentation",
      text: "Téléchargez la brochure commerciale complète du Verdelago Resort, en portugais ou en anglais.",
    },
    related: {
      eyebrow: "Également disponible",
      title: "Autres représentations de Rui Da Cruz",
    },
    fase6: {
      eyebrow: "Lancement",
      title: "Phase 6 — la dernière phase du Verdelago Resort",
      subtitle: "Une nouvelle occasion de découvrir le Verdelago",
      p1: "Le Verdelago Resort présente la phase 6, dernière phase de commercialisation du projet, désormais avancée afin de répondre à la demande de biens immobiliers plus spacieux et bénéficiant d'un emplacement privilégié au sein du complexe.",
      p2: "Cette dernière phase comprend 21 logements, dont 4 de type T4, soigneusement sélectionnés pour offrir une expérience de vie unique, en harmonie avec la nature et à proximité des principales infrastructures de Verdelago.",
      h1: "Un emplacement privilégié",
      p3: "Les deux lots qui composent cette phase bénéficient d'un emplacement particulièrement prisé, en raison de leur proximité avec le club, le spa et l'accès à la plage.",
      p4: "La combinaison d'espaces généreux, d'un emplacement idéal et de l'accès aux commodités du complexe fait de cette dernière phase une opportunité unique pour ceux qui recherchent une propriété dans l'une des destinations les plus exclusives de l'Algarve.",
      h2: "La dernière occasion d'acheter",
      p5: "Avec le lancement de la phase 6, Verdelago entre dans sa dernière phase de commercialisation, offrant ainsi l'opportunité d'acquérir un bien immobilier au sein d'un complexe conçu pour offrir un cadre de vie unique, en harmonie avec la nature et en bord de mer.",
      p6: "Découvrez les types de logements, les emplacements et les prix disponibles, ainsi que les dernières opportunités d'achat au Verdelago Resort.",
      p7: "Pour plus d'informations ou pour prendre rendez-vous, n'hésitez pas à nous contacter.",
      statTotal: "fractions à ce stade",
      statAvailable: "encore disponibles",
      ctaUnits: "Afficher les fractions et les valeurs",
      ctaContact: "Prendre rendez-vous",
      imageAlt: "Club et spa du Verdelago Resort",
    },
    unidades: {
      eyebrow: "Unités",
      title: "Unités disponibles",
      description: "Logements disponibles par phase, avec leur type et leur prix.",
      legendToggle: "Que signifient ces colonnes ?",
      legendLoteLabel: "Lot",
      legendLoteText: "l'immeuble/le bloc situé au sein du complexe. Une parcelle comportant plusieurs lots correspond à un grand immeuble comprenant plusieurs appartements.",
      legendFracaoLabel: "Fraction",
      legendFracaoText: "le code officiel du logement : le premier chiffre correspond à l'étage (0 = rez-de-chaussée, 1 = 1er étage...) et la lettre indique la position au sein de cet étage.",
      legendTipologiaLabel: "Typologie",
      legendTipologiaText: "T2/T3 correspond au nombre de chambres ; la lettre (A, B, C, D) désigne un agencement différent comportant le même nombre de chambres — voir les plans ci-dessus.",
      colLote: "Lot",
      colFracao: "Fraction",
      colTipologia: "Typologie",
      colValor: "Montant",
      fracoesLabel: "fractions",
      verTodas: "Tout afficher",
      brevemente: "À bientôt",
      vendido: "Vendu",
    },
    featured: {
      eyebrow: "Options à la une",
      title: "Quelques suggestions pour commencer",
      description: "Une sélection rapide parmi les unités disponibles — le tableau complet se trouve ci-dessous.",
      brevemente: "À bientôt",
    },
    form: {
      eyebrow: "Contact", title: "Découvrez les unités actuellement disponibles",
      subtitle: "Typologies, plans, grille tarifaire et conditions d'achat. Réponse sous quelques heures.",
      name: "Nom", countryCode: "Indicatif du pays", phoneInvalid: "Numéro incomplet pour le pays sélectionné.",
      phone: "Téléphone / WhatsApp", message: "Message (facultatif)",
      consent: "J'accepte que mes données soient traitées à des fins de prospection commerciale.",
      submit: "Demander Plus d'Informations", submitting: "Envoi…",
      success: "Bien reçu. Rui Da Cruz vous contactera prochainement.",
      error: "L'envoi a échoué. Veuillez réessayer ou nous contacter via WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Société de courtage immobilier, S.A.",
      rights: "Représentation exclusive par Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Bonjour Rui, je suis intéressé(e) par les appartements du Verdelago Resort, en Algarve. J'aimerais plus d'informations.",
    lightbox: { close: "Fermer", previous: "Précédent", next: "Suivant", video: "Vidéo" },
  },
  it: {
    meta: {
      title: "Verdelago Resort | Appartamenti T2 e T3 in Algarve — Rui Da Cruz",
      description:
        "Appartamenti T2 e T3 al Verdelago Resort, un complesso turistico a 5 stelle tra Altura e Praia Verde, Algarve. Accesso diretto alla spiaggia, SPA, piscine e Resort Club. Rappresentato da Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Diretto", sobre: "Informazioni", contacto: "Contatti", guia: "Guida", faq: "FAQ", vender: "Vendere" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort a 5 Stelle", "T2 e T3", "Accesso Diretto alla Spiaggia", "Idoneo per NHR"],
      title: "Dove l'Atlantico incontra la tranquillità dell'Algarve",
      lede: "Un santuario costiero tra Altura e Praia Verde — natura preservata, servizi di eccellenza e una collezione ridotta di residenze.",
      priceFrom: "Da 880.000 €",
      priceNote: "Appartamenti T2 · Fasi 4-6",
      specs: [
        { label: "Posizione", value: "Altura, Castro Marim" },
        { label: "Tipologie", value: "T2 e T3" },
        { label: "Certificazione", value: "Green Globe · Green Key" },
        { label: "Consegna", value: "Fasi 4, 5 e 6" },
      ],
      ctaPrimary: "Richiedi Maggiori Informazioni",
      ctaWhatsapp: "Contatta via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Consulente Immobiliare · RE/MAX Vantagem Platina · Certificato RE/MAX Collection",
    },
    narrative: {
      eyebrow: "Il Complesso",
      paragraphs: [
        "Più di un complesso residenziale, Verdelago offre uno stile di vita raffinato, in cui comfort, natura e servizi di eccellenza convivono in perfetta armonia — uno dei punti di riferimento del segmento residenziale e turistico di lusso in Algarve.",
        "Situato tra Altura e Praia Verde, con accesso diretto alla spiaggia tramite passerelle integrate nel paesaggio naturale, questo resort a 5 stelle si distingue per la bassa densità edilizia, l'eccellenza costruttiva e l'architettura contemporanea — un impegno autentico verso la sostenibilità, riconosciuto a livello internazionale dalle certificazioni Green Globe e Green Key.",
        "Il resort offre un insieme di infrastrutture e servizi premium: hotel a 5 stelle, Resort Club, SPA & Wellness, piscine, palestra, Kids Club, ampi spazi verdi, ristoranti e sicurezza e gestione integrate — tutto pensato per vivere appieno, a pochi passi da casa.",
        "Che sia per residenza permanente, seconda casa o investimento, Verdelago Resort offre una combinazione rara di esclusività, privacy e qualità della vita, in uno degli ultimi paesaggi intatti della costa dell'Algarve.",
      ],
      closing: "L'ultimo paradiso dell'Algarve. Tra la natura e il mare.",
    },
    amenities: {
      eyebrow: "Nel Dettaglio",
      items: [
        "Hotel a 5 stelle", "Resort Club", "SPA & Wellness", "Piscine esterne",
        "Palestra attrezzata", "Kids Club", "Campi da padel", "Green Park e ampi spazi verdi",
        "Ristoranti e aree relax", "Sicurezza e gestione integrata del resort",
        "Parcheggio coperto", "Accesso diretto alla spiaggia tramite passerelle",
      ],
    },
    gallery: {
      eyebrow: "Galleria", title: "Un luogo unico dove vivere",
      viewCursor: "Vedi", viewFullGallery: "Vedi la Galleria Completa", photos: "foto",
      photosAndVideo: "foto + video", playVideo: "Riproduci il video del Verdelago",
      viewPhoto: "Vedi foto", previousPhoto: "Foto precedente", nextPhoto: "Foto successiva",
    },
    floorplans: {
      eyebrow: "Planimetrie", title: "Tipologie T2 e T3", cta: "Vedi Planimetrie",
      credit: "Verdelago Resort · Documento Commerciale",
    },
    location: {
      eyebrow: "Posizione", title: "Altura, Castro Marim — Algarve",
      text: "Sulla costa orientale dell'Algarve, tra Altura e Praia Verde — una zona ricca di natura, spiagge incontaminate e tradizione, con accesso diretto al mare tramite passerelle integrate nel paesaggio.",
      mapLink: "Vedi sulla mappa",
    },
    lifestyle: {
      eyebrow: "Vivere a Verdelago",
      title: "Dove la vita è fatta di piccoli momenti",
      lede: "Più che un semplice alloggio, il Verdelago offre uno stile di vita: tra la spiaggia, la piscina e il verde circostante, ogni giorno trova il proprio momento di relax.",
      moments: ["Cocktail d'autore al tramonto", "Spiaggia protetta, a pochi passi da casa", "Kids Club per mattinate più tranquille", "Trattamenti benessere su misura", "Pool Club e Beach Club", "Sport all'aria aperta, tutto l'anno"],
    },
    investment: {
      eyebrow: "Investimento",
      title: "Un'acquisizione pensata per generare profitti",
      items: [
        { title: "Residente non abituale", text: "Il Portogallo offre un regime fiscale vantaggioso per i nuovi residenti — condizioni da verificare con il proprio consulente fiscale, ma un fattore rilevante per chi intende stabilirsi in Algarve." },
        { title: "Programma di locazione", text: "Il 75% dei ricavi netti derivanti dalla locazione spetta al proprietario; il restante 25% copre i costi di gestione della società che gestisce il resort — senza che il proprietario debba preoccuparsi degli aspetti operativi." },
        { title: "Struttura dei pagamenti", text: "25.000 € di caparra, il 25% alla firma del CPCV, il 35% al completamento della struttura e il restante 40% all'atto pubblico." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "Un impegno autentico a favore della sostenibilità, riconosciuto a livello internazionale: bassa densità edilizia, gestione responsabile delle risorse idriche e energetiche e rispetto per il paesaggio naturale dell’Algarve.",
    },
    brochure: {
      eyebrow: "Documentazione",
      text: "Scarica la brochure commerciale completa del Verdelago Resort, in portoghese o in inglese.",
    },
    related: {
      eyebrow: "Disponibile anche",
      title: "Altri immobili rappresentati da Rui Da Cruz",
    },
    fase6: {
      eyebrow: "Lancio",
      title: "Fase 6 — l'ultima fase del Verdelago Resort",
      subtitle: "Una nuova occasione per vivere il Verdelago",
      p1: "Il Verdelago Resort presenta la Fase 6, l'ultima e definitiva fase di vendita del progetto, ora anticipata per rispondere alla domanda di immobili più spaziosi e situati in una posizione privilegiata all'interno del resort.",
      p2: "Quest'ultima fase è composta da 21 unità, tra cui 4 appartamenti di tipologia T4, accuratamente selezionati per offrire un'esperienza abitativa unica, immersa nella natura e vicina alle principali attrazioni di Verdelago.",
      h1: "Una posizione privilegiata",
      p3: "I due lotti che compongono questa fase godono di una posizione particolarmente privilegiata, grazie alla loro vicinanza al Club, alla SPA e all’accesso alla spiaggia.",
      p4: "La combinazione di spazi generosi, posizione strategica e accesso ai servizi del resort rende questa ultima fase un’opportunità unica per chi è alla ricerca di un immobile in una delle destinazioni più esclusive dell’Algarve.",
      h2: "L'ultima occasione per acquistarlo",
      p5: "Con il lancio della Fase 6, Verdelago entra nella sua ultima fase di vendita, offrendo l'opportunità di acquistare un immobile in un resort progettato per garantire uno stile di vita esclusivo, in armonia con la natura e in riva al mare.",
      p6: "Scopri le tipologie, le ubicazioni e i prezzi disponibili e scopri le ultime opportunità di acquisto al Verdelago Resort.",
      p7: "Per ulteriori informazioni o per fissare un appuntamento, vi invitiamo a contattarci.",
      statTotal: "frazioni in questa fase",
      statAvailable: "ancora disponibili",
      ctaUnits: "Visualizza frazioni e valori",
      ctaContact: "Prenota una visita",
      imageAlt: "Club e SPA del Verdelago Resort",
    },
    unidades: {
      eyebrow: "Unità",
      title: "Unità disponibili",
      description: "Unità disponibili per fase, con tipologia e prezzo.",
      legendToggle: "Cosa significano queste colonne?",
      legendLoteLabel: "Lotto",
      legendLoteText: "l'edificio/il blocco all'interno del resort. Un lotto con diverse frazioni è un edificio più grande, con diversi appartamenti.",
      legendFracaoLabel: "Frazione",
      legendFracaoText: "il codice ufficiale dell'unità: la prima cifra indica il piano (0 = piano terra, 1 = 1° piano...) e la lettera indica la posizione all'interno di quel piano.",
      legendTipologiaLabel: "Tipologia",
      legendTipologiaText: "T2/T3 indica il numero di camere; la lettera (A, B, C, D) indica una pianta diversa con lo stesso numero di camere — si vedano le piante riportate sopra.",
      colLote: "Lotto",
      colFracao: "Frazione",
      colTipologia: "Tipologia",
      colValor: "Valore",
      fracoesLabel: "frazioni",
      verTodas: "vedi tutto",
      brevemente: "A breve",
      vendido: "Venduto",
    },
    featured: {
      eyebrow: "Opzioni in primo piano",
      title: "Alcune proposte per iniziare",
      description: "Una rapida selezione tra le unità disponibili — la tabella completa è riportata più in basso.",
      brevemente: "A breve",
    },
    form: {
      eyebrow: "Contatti", title: "Scopri le unità attualmente disponibili",
      subtitle: "Tipologie, planimetrie, listino prezzi e condizioni d'acquisto. Risposta entro poche ore.",
      name: "Nome", countryCode: "Prefisso internazionale", phoneInvalid: "Numero non valido per il Paese selezionato.",
      phone: "Telefono / WhatsApp", message: "Messaggio (facoltativo)",
      consent: "Acconsento al trattamento dei miei dati a fini di contatto commerciale.",
      submit: "Richiedi Maggiori Informazioni", submitting: "Invio…",
      success: "Ricevuto. Rui Da Cruz ti contatterà a breve.",
      error: "Non è stato possibile inviare il messaggio. Riprova oppure contattaci tramite WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Società di intermediazione immobiliare, S.A.",
      rights: "Rappresentanza esclusiva a cura di Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Ciao Rui, sono interessato/a agli appartamenti del Verdelago Resort, in Algarve. Vorrei maggiori informazioni.",
    lightbox: { close: "Chiudi", previous: "Precedente", next: "Successiva", video: "Video" },
  },
  de: {
    meta: {
      title: "Verdelago Resort | T2- und T3-Wohnungen an der Algarve — Rui Da Cruz",
      description:
        "T2- und T3-Wohnungen im Verdelago Resort, einer 5-Sterne-Ferienanlage zwischen Altura und Praia Verde an der Algarve. Direkter Strandzugang, SPA, Pools und Resort Club. Vertreten von Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp direkt", sobre: "Über", contacto: "Kontakt", guia: "Leitfaden", faq: "FAQ", vender: "Verkaufen" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["5-Sterne-Resort", "T2 & T3", "Direkter Strandzugang", "NHR-berechtigt"],
      title: "Wo der Atlantik auf die Ruhe der Algarve trifft",
      lede: "Ein Küstenrefugium zwischen Altura und Praia Verde — unberührte Natur, erstklassiger Service und eine begrenzte Auswahl an Residenzen.",
      priceFrom: "Ab 880.000 €",
      priceNote: "T2-Wohnungen · Phasen 4 bis 6",
      specs: [
        { label: "Lage", value: "Altura, Castro Marim" },
        { label: "Wohnungstypen", value: "T2 & T3" },
        { label: "Zertifizierung", value: "Green Globe · Green Key" },
        { label: "Fertigstellung", value: "Phasen 4, 5 & 6" },
      ],
      ctaPrimary: "Weitere Informationen anfragen",
      ctaWhatsapp: "Über WhatsApp sprechen",
      agentName: "Rui Da Cruz",
      agentTitle: "Immobilienberater · RE/MAX Vantagem Platina · RE/MAX Collection zertifiziert",
    },
    narrative: {
      eyebrow: "Die Anlage",
      paragraphs: [
        "Verdelago ist mehr als eine Wohnanlage — hier verschmelzen Komfort, Natur und erstklassiger Service zu einem raffinierten Lebensstil und setzen damit einen Maßstab im Luxus-Wohn- und Tourismussegment der Algarve.",
        "Zwischen Altura und Praia Verde gelegen, mit direktem Strandzugang über Holzstege, die sich harmonisch in die Naturlandschaft einfügen, überzeugt dieses 5-Sterne-Resort durch niedrige Bebauungsdichte, hervorragende Bauqualität und zeitgemäße Architektur — ein echtes Bekenntnis zur Nachhaltigkeit, international anerkannt durch die Zertifizierungen Green Globe und Green Key.",
        "Das Resort bietet erstklassige Infrastruktur und Dienstleistungen: ein 5-Sterne-Hotel, Resort Club, SPA & Wellness, Schwimmbäder, Fitnessstudio, Kids Club, weitläufige Grünflächen, Restaurants sowie integrierte Sicherheit und Verwaltung — alles für ein rundum erfülltes Leben, nur wenige Schritte von zu Hause entfernt.",
        "Ob als Hauptwohnsitz, Zweitwohnsitz oder Investition — Verdelago Resort bietet eine seltene Kombination aus Exklusivität, Privatsphäre und Lebensqualität in einer der letzten unberührten Landschaften der Algarve-Küste.",
      ],
      closing: "Das letzte Paradies der Algarve. Zwischen Natur und Meer.",
    },
    amenities: {
      eyebrow: "Im Detail",
      items: [
        "5-Sterne-Hotel", "Resort Club", "SPA & Wellness", "Außenpools",
        "Voll ausgestattetes Fitnessstudio", "Kids Club", "Padel-Plätze", "Green Park und weitläufige Grünflächen",
        "Restaurants und Freizeitbereiche", "Integrierte Sicherheit und Verwaltung des Resorts",
        "Überdachter Parkplatz", "Direkter Strandzugang über Holzstege",
      ],
    },
    gallery: {
      eyebrow: "Galerie", title: "Ein einzigartiger Ort zum Leben",
      viewCursor: "Ansehen", viewFullGallery: "Vollständige Galerie ansehen", photos: "Fotos",
      photosAndVideo: "Fotos + Video", playVideo: "Verdelago-Video abspielen",
      viewPhoto: "Foto ansehen", previousPhoto: "Vorheriges Foto", nextPhoto: "Nächstes Foto",
    },
    floorplans: {
      eyebrow: "Grundrisse", title: "Wohnungstypen T2 und T3", cta: "Grundrisse ansehen",
      credit: "Verdelago Resort · Verkaufsunterlagen",
    },
    location: {
      eyebrow: "Lage", title: "Altura, Castro Marim — Algarve",
      text: "An der Ostküste der Algarve, zwischen Altura und Praia Verde — eine Region reich an Natur, unberührten Stränden und Tradition, mit direktem Meerzugang über Holzstege, die sich in die Landschaft einfügen.",
      mapLink: "Auf der Karte ansehen",
    },
    lifestyle: {
      eyebrow: "Leben in Verdelago",
      title: "Wo das Leben aus kleinen Momenten besteht",
      lede: "Das Verdelago ist mehr als nur eine Unterkunft – es bietet einen ganz eigenen Lebensrhythmus: Zwischen Strand, Pool und der umgebenden Natur findet jeder Tag seinen ganz eigenen Moment der Ruhe.",
      moments: ["Hausgemachte Cocktails bei Sonnenuntergang", "Ein geschützter Strand, nur wenige Schritte vom Haus entfernt", "Kids Club für entspannte Vormittage", "Maßgeschneiderte Wellness-Behandlungen", "Pool-Club und Beach-Club", "Outdoor-Sport, das ganze Jahr über"],
    },
    investment: {
      eyebrow: "Investition",
      title: "Eine Anschaffung, die sich auszahlen soll",
      items: [
        { title: "Nicht-ständiger Einwohner", text: "Portugal bietet neuen Einwohnern ein vorteilhaftes Steuersystem – die genauen Bedingungen sollten Sie mit Ihrem Steuerberater klären, doch dies ist ein wichtiger Faktor für alle, die die Algarve als Wohnsitz in Betracht ziehen." },
        { title: "Mietprogramm", text: "75 % der Netto-Mieteinnahmen verbleiben beim Eigentümer; die restlichen 25 % decken die Verwaltungskosten des Resortbetreibers ab – ohne dass Sie sich um den Betrieb kümmern müssen." },
        { title: "Zahlungsstruktur", text: "25.000 € Anzahlung, 25 % bei Unterzeichnung des Vorvertrags (CPCV), 35 % bei Fertigstellung des Rohbaus und die restlichen 40 % bei der notariellen Beurkundung." },
      ],
    },
    certification: {
      badges: ['Green Globe', 'Green Key'],
      text: "Ein echtes, international anerkanntes Engagement für Nachhaltigkeit – geringe Bebauungsdichte, bewusster Umgang mit Wasser und Energie sowie Respekt vor der natürlichen Landschaft der Algarve.",
    },
    brochure: {
      eyebrow: "Dokumentation",
      text: "Laden Sie die vollständige Broschüre zum Verdelago Resort auf Portugiesisch oder Englisch herunter.",
    },
    related: {
      eyebrow: "Ebenfalls erhältlich",
      title: "Weitere von Rui Da Cruz vertretene Immobilien",
    },
    fase6: {
      eyebrow: "Veröffentlichung",
      title: "Phase 6 – die letzte Phase des Verdelago Resorts",
      subtitle: "Eine neue Gelegenheit, das Verdelago zu erleben",
      p1: "Das Verdelago Resort präsentiert Phase 6, die letzte und abschließende Verkaufsphase des Projekts, die nun vorgezogen wurde, um der Nachfrage nach größeren Immobilien in bester Lage innerhalb des Resorts gerecht zu werden.",
      p2: "Diese letzte Bauphase umfasst 21 Wohneinheiten, darunter 4 Vier-Zimmer-Wohnungen, die sorgfältig ausgewählt wurden, um ein einzigartiges Wohnerlebnis zu bieten, das sich harmonisch in die Natur einfügt und in unmittelbarer Nähe zu den wichtigsten Einrichtungen von Verdelago liegt.",
      h1: "Eine erstklassige Lage",
      p3: "Die beiden Gebäude, die zu dieser Bauphase gehören, profitieren von einer besonders begehrten Lage aufgrund ihrer Nähe zum Club, zum Spa und zum Strandzugang.",
      p4: "Die Kombination aus großzügigen Räumlichkeiten, der Lage und dem Zugang zu den Annehmlichkeiten des Resorts macht diese letzte Bauphase zu einer einzigartigen Gelegenheit für alle, die eine Immobilie in einem der exklusivsten Reiseziele der Algarve suchen.",
      h2: "Die letzte Gelegenheit zum Kauf",
      p5: "Mit dem Start von Phase 6 tritt Verdelago in die letzte Verkaufsphase ein – eine Gelegenheit, eine Immobilie in einem Resort zu erwerben, das darauf ausgelegt ist, ein einzigartiges Lebenserlebnis im Einklang mit der Natur und direkt am Meer zu bieten.",
      p6: "Informieren Sie sich über die verfügbaren Wohnungstypen, Lagen und Preise und entdecken Sie die neuesten Kaufangebote im Verdelago Resort.",
      p7: "Für weitere Informationen oder um einen Besichtigungstermin zu vereinbaren, nehmen Sie bitte Kontakt mit uns auf.",
      statTotal: "Brüche in dieser Phase",
      statAvailable: "noch verfügbar",
      ctaUnits: "Brüche und Werte anzeigen",
      ctaContact: "Besuch vereinbaren",
      imageAlt: "Club und Spa des Verdelago Resorts",
    },
    unidades: {
      eyebrow: "Einheiten",
      title: "Verfügbare Einheiten",
      description: "Verfügbare Einheiten pro Bauphase, mit Typ und Preis.",
      legendToggle: "Was bedeuten diese Spalten?",
      legendLoteLabel: "Los",
      legendLoteText: "das Gebäude/der Wohnblock innerhalb des Resorts. Ein Grundstück mit mehreren Einheiten ist ein größeres Gebäude mit mehreren Wohnungen.",
      legendFracaoLabel: "Einheit",
      legendFracaoText: "Die offizielle Nummer der Wohnung: Die erste Ziffer gibt das Stockwerk an (0 = Erdgeschoss, 1 = 1. Stock …), und der Buchstabe steht für die Position innerhalb dieses Stockwerks.",
      legendTipologiaLabel: "Typologie",
      legendTipologiaText: "T2/T3 steht für die Anzahl der Zimmer; der Buchstabe (A, B, C, D) bezeichnet einen anderen Grundriss mit derselben Anzahl an Zimmern – siehe die Grundrisse weiter oben.",
      colLote: "Los",
      colFracao: "Einheit",
      colTipologia: "Typologie",
      colValor: "Wert",
      fracoesLabel: "Einheiten",
      verTodas: "Alle anzeigen",
      brevemente: "In Kürze",
      vendido: "Verkauft",
    },
    featured: {
      eyebrow: "Empfohlene Optionen",
      title: "Ein paar Vorschläge für den Anfang",
      description: "Eine schnelle Auswahl aus den verfügbaren Einheiten – die vollständige Tabelle finden Sie weiter unten.",
      brevemente: "In Kürze",
    },
    form: {
      eyebrow: "Kontakt", title: "Entdecken Sie die aktuell verfügbaren Einheiten",
      subtitle: "Wohnungstypen, Grundrisse, Preise und Kaufbedingungen. Antwort innerhalb weniger Stunden.",
      name: "Name", countryCode: "Ländercode", phoneInvalid: "Die Nummer ist für das ausgewählte Land unvollständig.",
      phone: "Telefon / WhatsApp", message: "Nachricht (optional)",
      consent: "Ich stimme der Verarbeitung meiner Daten zu Zwecken der geschäftlichen Kontaktaufnahme zu.",
      submit: "Weitere Informationen anfragen", submitting: "Wird gesendet…",
      success: "Verstanden. Rui Da Cruz wird sich in Kürze bei Ihnen melden.",
      error: "Das Senden ist nicht gelungen. Bitte versuchen Sie es erneut oder kontaktieren Sie uns über WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Immobilienmaklergesellschaft, S.A.",
      rights: "Exklusive Vertretung durch Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Hallo Rui, ich interessiere mich für die Wohnungen im Verdelago Resort an der Algarve. Ich hätte gerne weitere Informationen.",
    lightbox: { close: "Schließen", previous: "Zurück", next: "Weiter", video: "Video" },
  },
} as const;

export const galleryImages = [
  { src: "/images/verdelago/03-apartamento.jpg", alt: { "pt-PT": "Vista aérea do resort junto ao mar", "pt-BR": "Vista aérea do resort junto ao mar", en: "Aerial view of the resort by the sea", es: "Vista aérea del resort junto al mar", fr: "Vue aérienne du resort en bord de mer", it: "Vista aerea del resort sul mare", de: "Luftaufnahme des Resorts am Meer" } },
  { src: "/images/verdelago/01-hero-humanizada.jpg", alt: { "pt-PT": "Vista humanizada do resort junto à natureza", "pt-BR": "Vista humanizada do resort junto à natureza", en: "Lifestyle view of the resort amid nature", es: "Vista humanizada del resort junto a la naturaleza", fr: "Vue lifestyle du resort au cœur de la nature", it: "Vista lifestyle del resort immerso nella natura", de: "Lifestyle-Ansicht des Resorts inmitten der Natur" } },
  { src: "/images/verdelago/02-humanizada.jpg", alt: { "pt-PT": "Ambiente de lazer do resort ao entardecer", "pt-BR": "Ambiente de lazer do resort ao entardecer", en: "Resort leisure setting at dusk", es: "Zona de ocio del resort al atardecer", fr: "Espace détente du resort au crépuscule", it: "Area relax del resort al tramonto", de: "Freizeitbereich des Resorts in der Abenddämmerung" } },
  { src: "/images/verdelago/04-apartamento.jpg", alt: { "pt-PT": "Sala de estar com vista para o resort", "pt-BR": "Sala de estar com vista para o resort", en: "Living room overlooking the resort", es: "Salón con vistas al resort", fr: "Salon avec vue sur le resort", it: "Soggiorno con vista sul resort", de: "Wohnzimmer mit Blick auf das Resort" } },
  { src: "/images/verdelago/05-spa.jpg", alt: { "pt-PT": "SPA & Wellness", "pt-BR": "Spa & wellness", en: "SPA & Wellness", es: "SPA y wellness", fr: "SPA & Wellness", it: "SPA & Wellness", de: "SPA & Wellness" } },
  { src: "/images/verdelago/06-spa.jpg", alt: { "pt-PT": "Piscina interior do SPA", "pt-BR": "Piscina interna do spa", en: "Indoor SPA pool", es: "Piscina interior del spa", fr: "Piscine intérieure du SPA", it: "Piscina interna della SPA", de: "Innenpool des SPA" } },
  { src: "/images/verdelago/07-praca-pinhal.jpg", alt: { "pt-PT": "Praça do Pinhal ao entardecer", "pt-BR": "Praça do Pinhal ao entardecer", en: "Praça do Pinhal square at dusk", es: "Praça do Pinhal al atardecer", fr: "Place Praça do Pinhal au crépuscule", it: "Praça do Pinhal al tramonto", de: "Praça do Pinhal in der Abenddämmerung" } },
  { src: "/images/verdelago/08-food-beverage.jpg", alt: { "pt-PT": "Gastronomia do resort", "pt-BR": "Gastronomia do resort", en: "Resort dining", es: "Gastronomía del resort", fr: "Restauration du resort", it: "Ristorazione del resort", de: "Gastronomie des Resorts" } },
  { src: "/images/verdelago/09-humanizada.jpg", alt: { "pt-PT": "Vida no resort", "pt-BR": "Vida no resort", en: "Life at the resort", es: "Vida en el resort", fr: "La vie au resort", it: "La vita nel resort", de: "Leben im Resort" } },
  { src: "/images/verdelago/10-ginasio.jpg", alt: { "pt-PT": "Ginásio equipado", "pt-BR": "Academia equipada", en: "Fully equipped gym", es: "Gimnasio equipado", fr: "Salle de sport équipée", it: "Palestra attrezzata", de: "Voll ausgestattetes Fitnessstudio" } },
  { src: "/images/verdelago/11-sports.jpg", alt: { "pt-PT": "Campo de padel do resort", "pt-BR": "Quadra de padel do resort", en: "Resort padel court", es: "Pista de pádel del resort", fr: "Terrain de padel du resort", it: "Campo da padel del resort", de: "Padel-Platz des Resorts" } },
  { src: "/images/verdelago/12-food-beverage.jpg", alt: { "pt-PT": "Gastronomia de excelência", "pt-BR": "Gastronomia de excelência", en: "Fine dining", es: "Gastronomía de excelencia", fr: "Gastronomie raffinée", it: "Gastronomia raffinata", de: "Exzellente Gastronomie" } },
] as const;
