export type Locale = "pt-PT" | "pt-BR" | "en" | "es" | "fr" | "it" | "de";

export const content = {
  "pt-PT": {
    meta: {
      title: "Verdelago Resort | Apartamentos T2 e T3 no Algarve — Rui Da Cruz",
      description:
        "Apartamentos T2 e T3 no Verdelago Resort, um empreendimento turístico de 5 estrelas entre Altura e a Praia Verde, Algarve. Acesso direto à praia, SPA, piscinas e Resort Club. Representação por Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direto", sobre: "Sobre", contacto: "Contacto" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort 5 Estrelas", "T2 e T3", "Acesso Direto à Praia", "Elegível para NHR"],
      title: "Onde o Atlântico encontra a tranquilidade do Algarve",
      lede: "Um santuário costeiro entre Altura e a Praia Verde — natureza preservada, serviços de excelência e uma coleção reduzida de residências.",
      priceFrom: "Desde 880.000 €",
      priceNote: "Apartamentos T2 · Fases 4 a 6",
      specs: [
        { label: "Localização", value: "Altura, Castro Marim" },
        { label: "Tipologias", value: "T2 e T3" },
        { label: "Certificação", value: "Green Globe · Green Key" },
        { label: "Entrega", value: "Fases 4, 5 e 6" },
      ],
      ctaPrimary: "Pedir Mais Informações",
      ctaWhatsapp: "Falar via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Consultor Imobiliário · RE/MAX Vantagem Platina · Certificado RE/MAX Collection",
    },
    narrative: {
      eyebrow: "O Empreendimento",
      paragraphs: [
        "Mais do que um empreendimento, o Verdelago proporciona um estilo de vida sofisticado, onde o conforto, a natureza e os serviços de excelência coexistem em perfeita harmonia — uma das referências do segmento residencial e turístico de luxo no Algarve.",
        "Localizado entre Altura e a Praia Verde, com acesso direto à praia através de passadiços integrados na paisagem natural, este resort de 5 estrelas distingue-se pela baixa densidade construtiva, pela excelência da construção e pela arquitetura contemporânea — um compromisso genuíno com a sustentabilidade, reconhecido internacionalmente pelas certificações Green Globe e Green Key.",
        "O resort disponibiliza um conjunto de infraestruturas e serviços premium: hotel de 5 estrelas, Resort Club, SPA & Wellness, piscinas, ginásio, Kids Club, amplas áreas verdes, restaurantes e segurança e gestão integrada — tudo pensado para uma vida em pleno, a poucos passos de casa.",
        "Seja para residência permanente, segunda habitação ou investimento, o Verdelago Resort oferece uma combinação rara de exclusividade, privacidade e qualidade de vida, numa das últimas paisagens intactas do litoral algarvio.",
      ],
      closing: "O último paraíso do Algarve. Entre a natureza e o mar.",
    },
    amenities: {
      eyebrow: "Em Detalhe",
      items: [
        "Hotel de 5 estrelas", "Resort Club", "SPA & Wellness", "Piscinas exteriores",
        "Ginásio equipado", "Kids Club", "Campos de padel", "Green Park e amplos espaços verdes",
        "Restaurantes e áreas de lazer", "Segurança e gestão integrada do resort",
        "Estacionamento coberto", "Acesso direto à praia por passadiços",
      ],
    },
    gallery: {
      eyebrow: "Galeria", title: "Um lugar único para viver",
      viewCursor: "Ver", viewFullGallery: "Ver Galeria Completa", photos: "fotos",
      viewPhoto: "Ver foto", previousPhoto: "Foto anterior", nextPhoto: "Próxima foto",
    },
    floorplans: {
      eyebrow: "Plantas", title: "Tipologias T2 e T3", cta: "Ver Plantas",
      credit: "Verdelago Resort · Documento Comercial",
    },
    location: {
      eyebrow: "Localização", title: "Altura, Castro Marim — Algarve",
      text: "No litoral leste do Algarve, entre Altura e a Praia Verde — uma zona rica em natureza, praias intactas e tradição, com acesso direto ao mar através de passadiços integrados na paisagem.",
      mapLink: "Ver no mapa",
    },
    form: {
      eyebrow: "Contacto", title: "Conheça as unidades atualmente disponíveis",
      subtitle: "Tipologias, plantas, tabela de preços e condições de aquisição. Resposta em poucas horas.",
      name: "Nome", countryCode: "Código do país", phoneInvalid: "Número incompleto para o país selecionado.",
      phone: "Telefone / WhatsApp", message: "Mensagem (opcional)",
      consent: "Concordo com o tratamento dos meus dados para fins de contacto comercial.",
      submit: "Pedir Mais Informações", submitting: "A enviar…",
      success: "Recebido. O Rui Da Cruz entrará em contacto em breve.",
      error: "Não foi possível enviar. Tente novamente ou contacte via WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedade de Mediação Imobiliária, S.A.",
      rights: "Representação exclusiva por Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Olá Rui, tenho interesse nos apartamentos do Verdelago Resort, no Algarve. Gostaria de mais informações.",
    lightbox: { close: "Fechar", previous: "Anterior", next: "Próxima" },
  },
  "pt-BR": {
    meta: {
      title: "Verdelago Resort | Apartamentos T2 e T3 no Algarve — Rui Da Cruz",
      description:
        "Apartamentos T2 e T3 no Verdelago Resort, um empreendimento turístico cinco estrelas entre Altura e a Praia Verde, Algarve, Portugal. Acesso direto à praia, spa, piscinas e Resort Club. Representação de Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direto", sobre: "Sobre", contacto: "Contato" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort Cinco Estrelas", "T2 e T3", "Acesso Direto à Praia", "Elegível para NHR"],
      title: "Onde o Atlântico encontra a tranquilidade do Algarve",
      lede: "Um santuário costeiro entre Altura e a Praia Verde — natureza preservada, serviços de excelência e uma coleção reduzida de residências.",
      priceFrom: "A partir de € 880.000",
      priceNote: "Apartamentos T2 · Fases 4 a 6",
      specs: [
        { label: "Localização", value: "Altura, Castro Marim" },
        { label: "Tipologias", value: "T2 e T3" },
        { label: "Certificação", value: "Green Globe · Green Key" },
        { label: "Entrega", value: "Fases 4, 5 e 6" },
      ],
      ctaPrimary: "Pedir Mais Informações",
      ctaWhatsapp: "Falar pelo WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Consultor Imobiliário · RE/MAX Vantagem Platina · Certificado RE/MAX Collection",
    },
    narrative: {
      eyebrow: "O Empreendimento",
      paragraphs: [
        "Mais do que um empreendimento, o Verdelago proporciona um estilo de vida sofisticado, onde o conforto, a natureza e serviços de excelência coexistem em perfeita harmonia — uma das referências do segmento residencial e turístico de luxo no Algarve.",
        "Localizado entre Altura e a Praia Verde, com acesso direto à praia por meio de passarelas integradas à paisagem natural, esse resort cinco estrelas se destaca pela baixa densidade construtiva, pela excelência da construção e pela arquitetura contemporânea — um compromisso genuíno com a sustentabilidade, reconhecido internacionalmente pelas certificações Green Globe e Green Key.",
        "O resort disponibiliza um conjunto de infraestruturas e serviços premium: hotel cinco estrelas, Resort Club, spa & wellness, piscinas, academia, kids club, amplas áreas verdes, restaurantes e segurança e gestão integrada — tudo pensado para uma vida plena, a poucos passos de casa.",
        "Seja para residência permanente, segunda casa ou investimento, o Verdelago Resort oferece uma combinação rara de exclusividade, privacidade e qualidade de vida, em uma das últimas paisagens intactas do litoral do Algarve.",
      ],
      closing: "O último paraíso do Algarve. Entre a natureza e o mar.",
    },
    amenities: {
      eyebrow: "Em Detalhes",
      items: [
        "Hotel cinco estrelas", "Resort Club", "Spa & wellness", "Piscinas externas",
        "Academia equipada", "Kids club", "Quadras de padel", "Green Park e amplas áreas verdes",
        "Restaurantes e áreas de lazer", "Segurança e gestão integrada do resort",
        "Estacionamento coberto", "Acesso direto à praia por passarelas",
      ],
    },
    gallery: {
      eyebrow: "Galeria", title: "Um lugar único para viver",
      viewCursor: "Ver", viewFullGallery: "Ver Galeria Completa", photos: "fotos",
      viewPhoto: "Ver foto", previousPhoto: "Foto anterior", nextPhoto: "Próxima foto",
    },
    floorplans: {
      eyebrow: "Plantas", title: "Tipologias T2 e T3", cta: "Ver Plantas",
      credit: "Verdelago Resort · Documento Comercial",
    },
    location: {
      eyebrow: "Localização", title: "Altura, Castro Marim — Algarve",
      text: "No litoral leste do Algarve, entre Altura e a Praia Verde — uma região rica em natureza, praias intactas e tradição, com acesso direto ao mar por passarelas integradas à paisagem.",
      mapLink: "Ver no mapa",
    },
    form: {
      eyebrow: "Contato", title: "Conheça as unidades disponíveis no momento",
      subtitle: "Tipologias, plantas, tabela de preços e condições de compra. Resposta em poucas horas.",
      name: "Nome", countryCode: "Código do país", phoneInvalid: "Número incompleto para o país selecionado.",
      phone: "Telefone / WhatsApp", message: "Mensagem (opcional)",
      consent: "Concordo com o tratamento dos meus dados para fins de contato comercial.",
      submit: "Pedir Mais Informações", submitting: "Enviando…",
      success: "Recebido. Rui Da Cruz entrará em contato em breve.",
      error: "Não foi possível enviar. Tente novamente ou entre em contato pelo WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedade de Mediação Imobiliária, S.A.",
      rights: "Representação exclusiva por Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Olá Rui, tenho interesse nos apartamentos do Verdelago Resort, no Algarve. Gostaria de mais informações.",
    lightbox: { close: "Fechar", previous: "Anterior", next: "Próxima" },
  },
  en: {
    meta: {
      title: "Verdelago Resort | T2 & T3 Apartments in the Algarve — Rui Da Cruz",
      description:
        "T2 and T3 apartments at Verdelago Resort, a 5-star tourist development between Altura and Praia Verde, Algarve. Direct beach access, SPA, pools and Resort Club. Represented by Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direct", sobre: "About", contacto: "Contact" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["5-Star Resort", "T2 & T3", "Direct Beach Access", "NHR Eligible"],
      title: "Where the Atlantic meets the tranquillity of the Algarve",
      lede: "A coastal sanctuary between Altura and Praia Verde — preserved nature, premium services and a limited collection of residences.",
      priceFrom: "From €880,000",
      priceNote: "T2 Apartments · Phases 4 to 6",
      specs: [
        { label: "Location", value: "Altura, Castro Marim" },
        { label: "Typologies", value: "T2 & T3" },
        { label: "Certification", value: "Green Globe · Green Key" },
        { label: "Delivery", value: "Phases 4, 5 & 6" },
      ],
      ctaPrimary: "Request More Information",
      ctaWhatsapp: "Talk via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Real Estate Consultant · RE/MAX Vantagem Platina · RE/MAX Collection Certified",
    },
    narrative: {
      eyebrow: "The Development",
      paragraphs: [
        "More than a development, Verdelago offers a sophisticated lifestyle where comfort, nature and premium services coexist in perfect harmony — one of the references of the luxury residential and tourism segment in the Algarve.",
        "Located between Altura and Praia Verde, with direct beach access via boardwalks integrated into the natural landscape, this 5-star resort stands out for its low building density, construction excellence and contemporary architecture — a genuine commitment to sustainability, internationally recognised through the Green Globe and Green Key certifications.",
        "The resort offers a range of premium infrastructure and services: a 5-star hotel, Resort Club, SPA & Wellness, swimming pools, gym, Kids Club, extensive green areas, restaurants and integrated security and management — all designed for a life lived fully, just steps from home.",
        "Whether for permanent residence, a second home or investment, Verdelago Resort offers a rare combination of exclusivity, privacy and quality of life, in one of the last untouched landscapes on the Algarve coastline.",
      ],
      closing: "The last paradise in the Algarve. Between nature and the sea.",
    },
    amenities: {
      eyebrow: "In Detail",
      items: [
        "5-star hotel", "Resort Club", "SPA & Wellness", "Outdoor pools",
        "Fully equipped gym", "Kids Club", "Padel courts", "Green Park and extensive green areas",
        "Restaurants and leisure areas", "Integrated resort security and management",
        "Covered parking", "Direct beach access via boardwalks",
      ],
    },
    gallery: {
      eyebrow: "Gallery", title: "A unique place to live",
      viewCursor: "View", viewFullGallery: "View Full Gallery", photos: "photos",
      viewPhoto: "View photo", previousPhoto: "Previous photo", nextPhoto: "Next photo",
    },
    floorplans: {
      eyebrow: "Floor Plans", title: "T2 & T3 Typologies", cta: "View Plans",
      credit: "Verdelago Resort · Commercial Document",
    },
    location: {
      eyebrow: "Location", title: "Altura, Castro Marim — Algarve",
      text: "On the eastern Algarve coastline, between Altura and Praia Verde — an area rich in nature, unspoiled beaches and tradition, with direct sea access via boardwalks integrated into the landscape.",
      mapLink: "View on map",
    },
    form: {
      eyebrow: "Contact", title: "Discover the units currently available",
      subtitle: "Typologies, floor plans, pricing and purchase terms. Response within hours.",
      name: "Name", countryCode: "Country code", phoneInvalid: "Incomplete number for the selected country.",
      phone: "Phone / WhatsApp", message: "Message (optional)",
      consent: "I agree to the processing of my data for commercial contact purposes.",
      submit: "Request More Information", submitting: "Sending…",
      success: "Received. Rui Da Cruz will be in touch shortly.",
      error: "Could not send. Please try again or reach out via WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedade de Mediação Imobiliária, S.A.",
      rights: "Exclusively represented by Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Hi Rui, I'm interested in the apartments at Verdelago Resort, in the Algarve. I'd like more information.",
    lightbox: { close: "Close", previous: "Previous", next: "Next" },
  },
  es: {
    meta: {
      title: "Verdelago Resort | Apartamentos T2 y T3 en el Algarve — Rui Da Cruz",
      description:
        "Apartamentos T2 y T3 en Verdelago Resort, un complejo turístico de 5 estrellas entre Altura y Praia Verde, Algarve. Acceso directo a la playa, SPA, piscinas y Resort Club. Representación de Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Directo", sobre: "Acerca de", contacto: "Contacto" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort de 5 Estrellas", "T2 y T3", "Acceso Directo a la Playa", "Elegible para NHR"],
      title: "Donde el Atlántico se encuentra con la tranquilidad del Algarve",
      lede: "Un santuario costero entre Altura y Praia Verde — naturaleza preservada, servicios de excelencia y una colección reducida de residencias.",
      priceFrom: "Desde 880.000 €",
      priceNote: "Apartamentos T2 · Fases 4 a 6",
      specs: [
        { label: "Ubicación", value: "Altura, Castro Marim" },
        { label: "Tipologías", value: "T2 y T3" },
        { label: "Certificación", value: "Green Globe · Green Key" },
        { label: "Entrega", value: "Fases 4, 5 y 6" },
      ],
      ctaPrimary: "Solicitar Más Información",
      ctaWhatsapp: "Hablar por WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Asesor Inmobiliario · RE/MAX Vantagem Platina · Certificado RE/MAX Collection",
    },
    narrative: {
      eyebrow: "El Complejo",
      paragraphs: [
        "Más que un complejo residencial, Verdelago ofrece un estilo de vida sofisticado, donde el confort, la naturaleza y los servicios de excelencia conviven en perfecta armonía — una de las referencias del segmento residencial y turístico de lujo en el Algarve.",
        "Situado entre Altura y Praia Verde, con acceso directo a la playa a través de pasarelas integradas en el paisaje natural, este resort de 5 estrellas destaca por su baja densidad constructiva, la excelencia de su construcción y su arquitectura contemporánea — un compromiso genuino con la sostenibilidad, reconocido internacionalmente por las certificaciones Green Globe y Green Key.",
        "El resort ofrece un conjunto de infraestructuras y servicios premium: hotel de 5 estrellas, Resort Club, SPA & Wellness, piscinas, gimnasio, Kids Club, amplias zonas verdes, restaurantes y seguridad y gestión integradas — todo pensado para vivir plenamente, a pocos pasos de casa.",
        "Ya sea para residencia permanente, segunda vivienda o inversión, Verdelago Resort ofrece una combinación excepcional de exclusividad, privacidad y calidad de vida, en uno de los últimos paisajes intactos del litoral del Algarve.",
      ],
      closing: "El último paraíso del Algarve. Entre la naturaleza y el mar.",
    },
    amenities: {
      eyebrow: "En Detalle",
      items: [
        "Hotel de 5 estrellas", "Resort Club", "SPA & Wellness", "Piscinas exteriores",
        "Gimnasio equipado", "Kids Club", "Pistas de pádel", "Green Park y amplias zonas verdes",
        "Restaurantes y zonas de ocio", "Seguridad y gestión integrada del resort",
        "Aparcamiento cubierto", "Acceso directo a la playa por pasarelas",
      ],
    },
    gallery: {
      eyebrow: "Galería", title: "Un lugar único para vivir",
      viewCursor: "Ver", viewFullGallery: "Ver Galería Completa", photos: "fotos",
      viewPhoto: "Ver foto", previousPhoto: "Foto anterior", nextPhoto: "Foto siguiente",
    },
    floorplans: {
      eyebrow: "Planos", title: "Tipologías T2 y T3", cta: "Ver Planos",
      credit: "Verdelago Resort · Documento Comercial",
    },
    location: {
      eyebrow: "Ubicación", title: "Altura, Castro Marim — Algarve",
      text: "En el litoral este del Algarve, entre Altura y Praia Verde — una zona rica en naturaleza, playas intactas y tradición, con acceso directo al mar a través de pasarelas integradas en el paisaje.",
      mapLink: "Ver en el mapa",
    },
    form: {
      eyebrow: "Contacto", title: "Conozca las unidades actualmente disponibles",
      subtitle: "Tipologías, planos, tabla de precios y condiciones de compra. Respuesta en pocas horas.",
      name: "Nombre", countryCode: "Código de país", phoneInvalid: "Número incompleto para el país seleccionado.",
      phone: "Teléfono / WhatsApp", message: "Mensaje (opcional)",
      consent: "Acepto que se traten mis datos con fines de contacto comercial.",
      submit: "Solicitar Más Información", submitting: "Enviando…",
      success: "Recibido. Rui Da Cruz se pondrá en contacto contigo en breve.",
      error: "No se ha podido enviar. Inténtalo de nuevo o contacta por WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Sociedad de Intermediación Inmobiliaria, S.A.",
      rights: "Representación exclusiva a cargo de Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Hola Rui, estoy interesado/a en los apartamentos de Verdelago Resort, en el Algarve. Me gustaría más información.",
    lightbox: { close: "Cerrar", previous: "Anterior", next: "Siguiente" },
  },
  fr: {
    meta: {
      title: "Verdelago Resort | Appartements T2 et T3 en Algarve — Rui Da Cruz",
      description:
        "Appartements T2 et T3 au Verdelago Resort, un complexe touristique 5 étoiles entre Altura et Praia Verde, en Algarve. Accès direct à la plage, SPA, piscines et Resort Club. Représentation par Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Direct", sobre: "À propos", contacto: "Contact" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort 5 Étoiles", "T2 et T3", "Accès Direct à la Plage", "Éligible au statut NHR"],
      title: "Là où l'Atlantique rencontre la tranquillité de l'Algarve",
      lede: "Un sanctuaire côtier entre Altura et Praia Verde — nature préservée, services d'excellence et une collection restreinte de résidences.",
      priceFrom: "À partir de 880 000 €",
      priceNote: "Appartements T2 · Phases 4 à 6",
      specs: [
        { label: "Emplacement", value: "Altura, Castro Marim" },
        { label: "Typologies", value: "T2 et T3" },
        { label: "Certification", value: "Green Globe · Green Key" },
        { label: "Livraison", value: "Phases 4, 5 et 6" },
      ],
      ctaPrimary: "Demander Plus d'Informations",
      ctaWhatsapp: "Contacter via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Conseiller Immobilier · RE/MAX Vantagem Platina · Certifié RE/MAX Collection",
    },
    narrative: {
      eyebrow: "Le Complexe",
      paragraphs: [
        "Plus qu'un complexe résidentiel, Verdelago propose un style de vie raffiné, où le confort, la nature et des services d'excellence coexistent en parfaite harmonie — l'une des références du segment résidentiel et touristique de luxe en Algarve.",
        "Situé entre Altura et Praia Verde, avec un accès direct à la plage via des passerelles intégrées au paysage naturel, ce resort 5 étoiles se distingue par sa faible densité de construction, l'excellence de sa construction et son architecture contemporaine — un engagement authentique envers la durabilité, reconnu internationalement par les certifications Green Globe et Green Key.",
        "Le resort propose un ensemble d'infrastructures et de services haut de gamme : hôtel 5 étoiles, Resort Club, SPA & Wellness, piscines, salle de sport, Kids Club, vastes espaces verts, restaurants ainsi qu'une sécurité et une gestion intégrées — tout pensé pour une vie pleinement vécue, à quelques pas de chez soi.",
        "Que ce soit pour une résidence principale, secondaire ou un investissement, Verdelago Resort offre une combinaison rare d'exclusivité, d'intimité et de qualité de vie, dans l'un des derniers paysages intacts du littoral de l'Algarve.",
      ],
      closing: "Le dernier paradis de l'Algarve. Entre la nature et la mer.",
    },
    amenities: {
      eyebrow: "En Détail",
      items: [
        "Hôtel 5 étoiles", "Resort Club", "SPA & Wellness", "Piscines extérieures",
        "Salle de sport équipée", "Kids Club", "Terrains de padel", "Green Park et vastes espaces verts",
        "Restaurants et espaces de loisirs", "Sécurité et gestion intégrées du resort",
        "Parking couvert", "Accès direct à la plage via passerelles",
      ],
    },
    gallery: {
      eyebrow: "Galerie", title: "Un lieu unique où vivre",
      viewCursor: "Voir", viewFullGallery: "Voir la Galerie Complète", photos: "photos",
      viewPhoto: "Voir la photo", previousPhoto: "Photo précédente", nextPhoto: "Photo suivante",
    },
    floorplans: {
      eyebrow: "Plans", title: "Typologies T2 et T3", cta: "Voir les Plans",
      credit: "Verdelago Resort · Document Commercial",
    },
    location: {
      eyebrow: "Emplacement", title: "Altura, Castro Marim — Algarve",
      text: "Sur le littoral est de l'Algarve, entre Altura et Praia Verde — une région riche en nature, en plages préservées et en tradition, avec un accès direct à la mer via des passerelles intégrées au paysage.",
      mapLink: "Voir sur la carte",
    },
    form: {
      eyebrow: "Contact", title: "Découvrez les unités actuellement disponibles",
      subtitle: "Typologies, plans, grille tarifaire et conditions d'achat. Réponse sous quelques heures.",
      name: "Nom", countryCode: "Indicatif du pays", phoneInvalid: "Numéro incomplet pour le pays sélectionné.",
      phone: "Téléphone / WhatsApp", message: "Message (facultatif)",
      consent: "J'accepte que mes données soient traitées à des fins de prospection commerciale.",
      submit: "Demander Plus d'Informations", submitting: "Envoi…",
      success: "Bien reçu. Rui Da Cruz vous contactera prochainement.",
      error: "L'envoi a échoué. Veuillez réessayer ou nous contacter via WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Société de courtage immobilier, S.A.",
      rights: "Représentation exclusive par Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Bonjour Rui, je suis intéressé(e) par les appartements du Verdelago Resort, en Algarve. J'aimerais plus d'informations.",
    lightbox: { close: "Fermer", previous: "Précédent", next: "Suivant" },
  },
  it: {
    meta: {
      title: "Verdelago Resort | Appartamenti T2 e T3 in Algarve — Rui Da Cruz",
      description:
        "Appartamenti T2 e T3 al Verdelago Resort, un complesso turistico a 5 stelle tra Altura e Praia Verde, Algarve. Accesso diretto alla spiaggia, SPA, piscine e Resort Club. Rappresentato da Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp Diretto", sobre: "Informazioni", contacto: "Contatti" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["Resort a 5 Stelle", "T2 e T3", "Accesso Diretto alla Spiaggia", "Idoneo per NHR"],
      title: "Dove l'Atlantico incontra la tranquillità dell'Algarve",
      lede: "Un santuario costiero tra Altura e Praia Verde — natura preservata, servizi di eccellenza e una collezione ridotta di residenze.",
      priceFrom: "Da 880.000 €",
      priceNote: "Appartamenti T2 · Fasi 4-6",
      specs: [
        { label: "Posizione", value: "Altura, Castro Marim" },
        { label: "Tipologie", value: "T2 e T3" },
        { label: "Certificazione", value: "Green Globe · Green Key" },
        { label: "Consegna", value: "Fasi 4, 5 e 6" },
      ],
      ctaPrimary: "Richiedi Maggiori Informazioni",
      ctaWhatsapp: "Contatta via WhatsApp",
      agentName: "Rui Da Cruz",
      agentTitle: "Consulente Immobiliare · RE/MAX Vantagem Platina · Certificato RE/MAX Collection",
    },
    narrative: {
      eyebrow: "Il Complesso",
      paragraphs: [
        "Più di un complesso residenziale, Verdelago offre uno stile di vita raffinato, in cui comfort, natura e servizi di eccellenza convivono in perfetta armonia — uno dei punti di riferimento del segmento residenziale e turistico di lusso in Algarve.",
        "Situato tra Altura e Praia Verde, con accesso diretto alla spiaggia tramite passerelle integrate nel paesaggio naturale, questo resort a 5 stelle si distingue per la bassa densità edilizia, l'eccellenza costruttiva e l'architettura contemporanea — un impegno autentico verso la sostenibilità, riconosciuto a livello internazionale dalle certificazioni Green Globe e Green Key.",
        "Il resort offre un insieme di infrastrutture e servizi premium: hotel a 5 stelle, Resort Club, SPA & Wellness, piscine, palestra, Kids Club, ampi spazi verdi, ristoranti e sicurezza e gestione integrate — tutto pensato per vivere appieno, a pochi passi da casa.",
        "Che sia per residenza permanente, seconda casa o investimento, Verdelago Resort offre una combinazione rara di esclusività, privacy e qualità della vita, in uno degli ultimi paesaggi intatti della costa dell'Algarve.",
      ],
      closing: "L'ultimo paradiso dell'Algarve. Tra la natura e il mare.",
    },
    amenities: {
      eyebrow: "Nel Dettaglio",
      items: [
        "Hotel a 5 stelle", "Resort Club", "SPA & Wellness", "Piscine esterne",
        "Palestra attrezzata", "Kids Club", "Campi da padel", "Green Park e ampi spazi verdi",
        "Ristoranti e aree relax", "Sicurezza e gestione integrata del resort",
        "Parcheggio coperto", "Accesso diretto alla spiaggia tramite passerelle",
      ],
    },
    gallery: {
      eyebrow: "Galleria", title: "Un luogo unico dove vivere",
      viewCursor: "Vedi", viewFullGallery: "Vedi la Galleria Completa", photos: "foto",
      viewPhoto: "Vedi foto", previousPhoto: "Foto precedente", nextPhoto: "Foto successiva",
    },
    floorplans: {
      eyebrow: "Planimetrie", title: "Tipologie T2 e T3", cta: "Vedi Planimetrie",
      credit: "Verdelago Resort · Documento Commerciale",
    },
    location: {
      eyebrow: "Posizione", title: "Altura, Castro Marim — Algarve",
      text: "Sulla costa orientale dell'Algarve, tra Altura e Praia Verde — una zona ricca di natura, spiagge incontaminate e tradizione, con accesso diretto al mare tramite passerelle integrate nel paesaggio.",
      mapLink: "Vedi sulla mappa",
    },
    form: {
      eyebrow: "Contatti", title: "Scopri le unità attualmente disponibili",
      subtitle: "Tipologie, planimetrie, listino prezzi e condizioni d'acquisto. Risposta entro poche ore.",
      name: "Nome", countryCode: "Prefisso internazionale", phoneInvalid: "Numero non valido per il Paese selezionato.",
      phone: "Telefono / WhatsApp", message: "Messaggio (facoltativo)",
      consent: "Acconsento al trattamento dei miei dati a fini di contatto commerciale.",
      submit: "Richiedi Maggiori Informazioni", submitting: "Invio…",
      success: "Ricevuto. Rui Da Cruz ti contatterà a breve.",
      error: "Non è stato possibile inviare il messaggio. Riprova oppure contattaci tramite WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Società di intermediazione immobiliare, S.A.",
      rights: "Rappresentanza esclusiva a cura di Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Ciao Rui, sono interessato/a agli appartamenti del Verdelago Resort, in Algarve. Vorrei maggiori informazioni.",
    lightbox: { close: "Chiudi", previous: "Precedente", next: "Successiva" },
  },
  de: {
    meta: {
      title: "Verdelago Resort | T2- und T3-Wohnungen an der Algarve — Rui Da Cruz",
      description:
        "T2- und T3-Wohnungen im Verdelago Resort, einer 5-Sterne-Ferienanlage zwischen Altura und Praia Verde an der Algarve. Direkter Strandzugang, SPA, Pools und Resort Club. Vertreten von Rui Da Cruz, RE/MAX Collection.",
    },
    nav: { whatsapp: "WhatsApp direkt", sobre: "Über", contacto: "Kontakt" },
    hero: { eyebrow: "Verdelago Resort", location: "Altura · Algarve" },
    overview: {
      tags: ["5-Sterne-Resort", "T2 & T3", "Direkter Strandzugang", "NHR-berechtigt"],
      title: "Wo der Atlantik auf die Ruhe der Algarve trifft",
      lede: "Ein Küstenrefugium zwischen Altura und Praia Verde — unberührte Natur, erstklassiger Service und eine begrenzte Auswahl an Residenzen.",
      priceFrom: "Ab 880.000 €",
      priceNote: "T2-Wohnungen · Phasen 4 bis 6",
      specs: [
        { label: "Lage", value: "Altura, Castro Marim" },
        { label: "Wohnungstypen", value: "T2 & T3" },
        { label: "Zertifizierung", value: "Green Globe · Green Key" },
        { label: "Fertigstellung", value: "Phasen 4, 5 & 6" },
      ],
      ctaPrimary: "Weitere Informationen anfragen",
      ctaWhatsapp: "Über WhatsApp sprechen",
      agentName: "Rui Da Cruz",
      agentTitle: "Immobilienberater · RE/MAX Vantagem Platina · RE/MAX Collection zertifiziert",
    },
    narrative: {
      eyebrow: "Die Anlage",
      paragraphs: [
        "Verdelago ist mehr als eine Wohnanlage — hier verschmelzen Komfort, Natur und erstklassiger Service zu einem raffinierten Lebensstil und setzen damit einen Maßstab im Luxus-Wohn- und Tourismussegment der Algarve.",
        "Zwischen Altura und Praia Verde gelegen, mit direktem Strandzugang über Holzstege, die sich harmonisch in die Naturlandschaft einfügen, überzeugt dieses 5-Sterne-Resort durch niedrige Bebauungsdichte, hervorragende Bauqualität und zeitgemäße Architektur — ein echtes Bekenntnis zur Nachhaltigkeit, international anerkannt durch die Zertifizierungen Green Globe und Green Key.",
        "Das Resort bietet erstklassige Infrastruktur und Dienstleistungen: ein 5-Sterne-Hotel, Resort Club, SPA & Wellness, Schwimmbäder, Fitnessstudio, Kids Club, weitläufige Grünflächen, Restaurants sowie integrierte Sicherheit und Verwaltung — alles für ein rundum erfülltes Leben, nur wenige Schritte von zu Hause entfernt.",
        "Ob als Hauptwohnsitz, Zweitwohnsitz oder Investition — Verdelago Resort bietet eine seltene Kombination aus Exklusivität, Privatsphäre und Lebensqualität in einer der letzten unberührten Landschaften der Algarve-Küste.",
      ],
      closing: "Das letzte Paradies der Algarve. Zwischen Natur und Meer.",
    },
    amenities: {
      eyebrow: "Im Detail",
      items: [
        "5-Sterne-Hotel", "Resort Club", "SPA & Wellness", "Außenpools",
        "Voll ausgestattetes Fitnessstudio", "Kids Club", "Padel-Plätze", "Green Park und weitläufige Grünflächen",
        "Restaurants und Freizeitbereiche", "Integrierte Sicherheit und Verwaltung des Resorts",
        "Überdachter Parkplatz", "Direkter Strandzugang über Holzstege",
      ],
    },
    gallery: {
      eyebrow: "Galerie", title: "Ein einzigartiger Ort zum Leben",
      viewCursor: "Ansehen", viewFullGallery: "Vollständige Galerie ansehen", photos: "Fotos",
      viewPhoto: "Foto ansehen", previousPhoto: "Vorheriges Foto", nextPhoto: "Nächstes Foto",
    },
    floorplans: {
      eyebrow: "Grundrisse", title: "Wohnungstypen T2 und T3", cta: "Grundrisse ansehen",
      credit: "Verdelago Resort · Verkaufsunterlagen",
    },
    location: {
      eyebrow: "Lage", title: "Altura, Castro Marim — Algarve",
      text: "An der Ostküste der Algarve, zwischen Altura und Praia Verde — eine Region reich an Natur, unberührten Stränden und Tradition, mit direktem Meerzugang über Holzstege, die sich in die Landschaft einfügen.",
      mapLink: "Auf der Karte ansehen",
    },
    form: {
      eyebrow: "Kontakt", title: "Entdecken Sie die aktuell verfügbaren Einheiten",
      subtitle: "Wohnungstypen, Grundrisse, Preise und Kaufbedingungen. Antwort innerhalb weniger Stunden.",
      name: "Name", countryCode: "Ländercode", phoneInvalid: "Die Nummer ist für das ausgewählte Land unvollständig.",
      phone: "Telefon / WhatsApp", message: "Nachricht (optional)",
      consent: "Ich stimme der Verarbeitung meiner Daten zu Zwecken der geschäftlichen Kontaktaufnahme zu.",
      submit: "Weitere Informationen anfragen", submitting: "Wird gesendet…",
      success: "Verstanden. Rui Da Cruz wird sich in Kürze bei Ihnen melden.",
      error: "Das Senden ist nicht gelungen. Bitte versuchen Sie es erneut oder kontaktieren Sie uns über WhatsApp.",
    },
    footer: {
      whatsapp: "+351 939 081 583",
      ami: "AMI 7772 · Prestígio Global – Immobilienmaklergesellschaft, S.A.",
      rights: "Exklusive Vertretung durch Rui Da Cruz, RE/MAX Vantagem Platina.",
    },
    whatsappMessage: "Hallo Rui, ich interessiere mich für die Wohnungen im Verdelago Resort an der Algarve. Ich hätte gerne weitere Informationen.",
    lightbox: { close: "Schließen", previous: "Zurück", next: "Weiter" },
  },
} as const;

export const galleryImages = [
  { src: "/images/verdelago/01-hero-humanizada.jpg", alt: { "pt-PT": "Vista humanizada do resort junto à natureza", "pt-BR": "Vista humanizada do resort junto à natureza", en: "Lifestyle view of the resort amid nature", es: "Vista humanizada del resort junto a la naturaleza", fr: "Vue lifestyle du resort au cœur de la nature", it: "Vista lifestyle del resort immerso nella natura", de: "Lifestyle-Ansicht des Resorts inmitten der Natur" } },
  { src: "/images/verdelago/02-humanizada.jpg", alt: { "pt-PT": "Ambiente de lazer do resort ao entardecer", "pt-BR": "Ambiente de lazer do resort ao entardecer", en: "Resort leisure setting at dusk", es: "Zona de ocio del resort al atardecer", fr: "Espace détente du resort au crépuscule", it: "Area relax del resort al tramonto", de: "Freizeitbereich des Resorts in der Abenddämmerung" } },
  { src: "/images/verdelago/03-apartamento.jpg", alt: { "pt-PT": "Vista aérea do resort junto ao mar", "pt-BR": "Vista aérea do resort junto ao mar", en: "Aerial view of the resort by the sea", es: "Vista aérea del resort junto al mar", fr: "Vue aérienne du resort en bord de mer", it: "Vista aerea del resort sul mare", de: "Luftaufnahme des Resorts am Meer" } },
  { src: "/images/verdelago/04-apartamento.jpg", alt: { "pt-PT": "Sala de estar com vista para o resort", "pt-BR": "Sala de estar com vista para o resort", en: "Living room overlooking the resort", es: "Salón con vistas al resort", fr: "Salon avec vue sur le resort", it: "Soggiorno con vista sul resort", de: "Wohnzimmer mit Blick auf das Resort" } },
  { src: "/images/verdelago/05-spa.jpg", alt: { "pt-PT": "SPA & Wellness", "pt-BR": "Spa & wellness", en: "SPA & Wellness", es: "SPA y wellness", fr: "SPA & Wellness", it: "SPA & Wellness", de: "SPA & Wellness" } },
  { src: "/images/verdelago/06-spa.jpg", alt: { "pt-PT": "Piscina interior do SPA", "pt-BR": "Piscina interna do spa", en: "Indoor SPA pool", es: "Piscina interior del spa", fr: "Piscine intérieure du SPA", it: "Piscina interna della SPA", de: "Innenpool des SPA" } },
  { src: "/images/verdelago/07-praca-pinhal.jpg", alt: { "pt-PT": "Praça do Pinhal ao entardecer", "pt-BR": "Praça do Pinhal ao entardecer", en: "Praça do Pinhal square at dusk", es: "Praça do Pinhal al atardecer", fr: "Place Praça do Pinhal au crépuscule", it: "Praça do Pinhal al tramonto", de: "Praça do Pinhal in der Abenddämmerung" } },
  { src: "/images/verdelago/08-food-beverage.jpg", alt: { "pt-PT": "Gastronomia do resort", "pt-BR": "Gastronomia do resort", en: "Resort dining", es: "Gastronomía del resort", fr: "Restauration du resort", it: "Ristorazione del resort", de: "Gastronomie des Resorts" } },
  { src: "/images/verdelago/09-humanizada.jpg", alt: { "pt-PT": "Vida no resort", "pt-BR": "Vida no resort", en: "Life at the resort", es: "Vida en el resort", fr: "La vie au resort", it: "La vita nel resort", de: "Leben im Resort" } },
  { src: "/images/verdelago/10-ginasio.jpg", alt: { "pt-PT": "Ginásio equipado", "pt-BR": "Academia equipada", en: "Fully equipped gym", es: "Gimnasio equipado", fr: "Salle de sport équipée", it: "Palestra attrezzata", de: "Voll ausgestattetes Fitnessstudio" } },
  { src: "/images/verdelago/11-sports.jpg", alt: { "pt-PT": "Campo de padel do resort", "pt-BR": "Quadra de padel do resort", en: "Resort padel court", es: "Pista de pádel del resort", fr: "Terrain de padel du resort", it: "Campo da padel del resort", de: "Padel-Platz des Resorts" } },
  { src: "/images/verdelago/12-food-beverage.jpg", alt: { "pt-PT": "Gastronomia de excelência", "pt-BR": "Gastronomia de excelência", en: "Fine dining", es: "Gastronomía de excelencia", fr: "Gastronomie raffinée", it: "Gastronomia raffinata", de: "Exzellente Gastronomie" } },
] as const;

export const floorplans = [
  { id: "t2a", src: "/images/verdelago/plantas/t2a.jpg", label: "T2A" },
  { id: "t2b", src: "/images/verdelago/plantas/t2b.jpg", label: "T2B" },
  { id: "t2c", src: "/images/verdelago/plantas/t2c.jpg", label: "T2C" },
  { id: "t2d", src: "/images/verdelago/plantas/t2d.jpg", label: "T2D" },
  { id: "t3b", src: "/images/verdelago/plantas/t3b.jpg", label: "T3B" },
  { id: "t3c", src: "/images/verdelago/plantas/t3c.jpg", label: "T3C" },
] as const;
